package com.work.shop.bean.mbproduct;

import java.util.Date;

public class MBProductSellerGoodsAttr {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_seller_goods_attr.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_seller_goods_attr.seller_code
     *
     * @mbggenerated
     */
    private String sellerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_seller_goods_attr.product_sys_code
     *
     * @mbggenerated
     */
    private String productSysCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_seller_goods_attr.attr_key_id
     *
     * @mbggenerated
     */
    private Integer attrKeyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_seller_goods_attr.attr_value_id
     *
     * @mbggenerated
     */
    private Integer attrValueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_seller_goods_attr.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_seller_goods_attr.sort
     *
     * @mbggenerated
     */
    private Byte sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_seller_goods_attr.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_seller_goods_attr.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_seller_goods_attr.last_update_user
     *
     * @mbggenerated
     */
    private String lastUpdateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_seller_goods_attr.last_update_date
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_seller_goods_attr.id
     *
     * @return the value of product_seller_goods_attr.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_seller_goods_attr.id
     *
     * @param id the value for product_seller_goods_attr.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_seller_goods_attr.seller_code
     *
     * @return the value of product_seller_goods_attr.seller_code
     *
     * @mbggenerated
     */
    public String getSellerCode() {
        return sellerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_seller_goods_attr.seller_code
     *
     * @param sellerCode the value for product_seller_goods_attr.seller_code
     *
     * @mbggenerated
     */
    public void setSellerCode(String sellerCode) {
        this.sellerCode = sellerCode == null ? null : sellerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_seller_goods_attr.product_sys_code
     *
     * @return the value of product_seller_goods_attr.product_sys_code
     *
     * @mbggenerated
     */
    public String getProductSysCode() {
        return productSysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_seller_goods_attr.product_sys_code
     *
     * @param productSysCode the value for product_seller_goods_attr.product_sys_code
     *
     * @mbggenerated
     */
    public void setProductSysCode(String productSysCode) {
        this.productSysCode = productSysCode == null ? null : productSysCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_seller_goods_attr.attr_key_id
     *
     * @return the value of product_seller_goods_attr.attr_key_id
     *
     * @mbggenerated
     */
    public Integer getAttrKeyId() {
        return attrKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_seller_goods_attr.attr_key_id
     *
     * @param attrKeyId the value for product_seller_goods_attr.attr_key_id
     *
     * @mbggenerated
     */
    public void setAttrKeyId(Integer attrKeyId) {
        this.attrKeyId = attrKeyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_seller_goods_attr.attr_value_id
     *
     * @return the value of product_seller_goods_attr.attr_value_id
     *
     * @mbggenerated
     */
    public Integer getAttrValueId() {
        return attrValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_seller_goods_attr.attr_value_id
     *
     * @param attrValueId the value for product_seller_goods_attr.attr_value_id
     *
     * @mbggenerated
     */
    public void setAttrValueId(Integer attrValueId) {
        this.attrValueId = attrValueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_seller_goods_attr.value
     *
     * @return the value of product_seller_goods_attr.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_seller_goods_attr.value
     *
     * @param value the value for product_seller_goods_attr.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_seller_goods_attr.sort
     *
     * @return the value of product_seller_goods_attr.sort
     *
     * @mbggenerated
     */
    public Byte getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_seller_goods_attr.sort
     *
     * @param sort the value for product_seller_goods_attr.sort
     *
     * @mbggenerated
     */
    public void setSort(Byte sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_seller_goods_attr.create_user
     *
     * @return the value of product_seller_goods_attr.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_seller_goods_attr.create_user
     *
     * @param createUser the value for product_seller_goods_attr.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_seller_goods_attr.create_date
     *
     * @return the value of product_seller_goods_attr.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_seller_goods_attr.create_date
     *
     * @param createDate the value for product_seller_goods_attr.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_seller_goods_attr.last_update_user
     *
     * @return the value of product_seller_goods_attr.last_update_user
     *
     * @mbggenerated
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_seller_goods_attr.last_update_user
     *
     * @param lastUpdateUser the value for product_seller_goods_attr.last_update_user
     *
     * @mbggenerated
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_seller_goods_attr.last_update_date
     *
     * @return the value of product_seller_goods_attr.last_update_date
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_seller_goods_attr.last_update_date
     *
     * @param lastUpdateDate the value for product_seller_goods_attr.last_update_date
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}