package com.work.shop.bean.mbproduct;

import java.util.Date;

public class MBProductLibBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.brand_code
     *
     * @mbggenerated
     */
    private String brandCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.brand_name
     *
     * @mbggenerated
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.first_letter
     *
     * @mbggenerated
     */
    private String firstLetter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.cname
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.ename
     *
     * @mbggenerated
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.brief
     *
     * @mbggenerated
     */
    private String brief;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.superiority
     *
     * @mbggenerated
     */
    private String superiority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.promotion_plan
     *
     * @mbggenerated
     */
    private String promotionPlan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.image_url
     *
     * @mbggenerated
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.image_big_url
     *
     * @mbggenerated
     */
    private String imageBigUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.package_url
     *
     * @mbggenerated
     */
    private String packageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.tag_url
     *
     * @mbggenerated
     */
    private String tagUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.last_update_user
     *
     * @mbggenerated
     */
    private String lastUpdateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.last_update_date
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_lib_brand.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.brand_id
     *
     * @return the value of product_lib_brand.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.brand_id
     *
     * @param brandId the value for product_lib_brand.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.brand_code
     *
     * @return the value of product_lib_brand.brand_code
     *
     * @mbggenerated
     */
    public String getBrandCode() {
        return brandCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.brand_code
     *
     * @param brandCode the value for product_lib_brand.brand_code
     *
     * @mbggenerated
     */
    public void setBrandCode(String brandCode) {
        this.brandCode = brandCode == null ? null : brandCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.brand_name
     *
     * @return the value of product_lib_brand.brand_name
     *
     * @mbggenerated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.brand_name
     *
     * @param brandName the value for product_lib_brand.brand_name
     *
     * @mbggenerated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.first_letter
     *
     * @return the value of product_lib_brand.first_letter
     *
     * @mbggenerated
     */
    public String getFirstLetter() {
        return firstLetter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.first_letter
     *
     * @param firstLetter the value for product_lib_brand.first_letter
     *
     * @mbggenerated
     */
    public void setFirstLetter(String firstLetter) {
        this.firstLetter = firstLetter == null ? null : firstLetter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.cname
     *
     * @return the value of product_lib_brand.cname
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.cname
     *
     * @param cname the value for product_lib_brand.cname
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.ename
     *
     * @return the value of product_lib_brand.ename
     *
     * @mbggenerated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.ename
     *
     * @param ename the value for product_lib_brand.ename
     *
     * @mbggenerated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.brief
     *
     * @return the value of product_lib_brand.brief
     *
     * @mbggenerated
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.brief
     *
     * @param brief the value for product_lib_brand.brief
     *
     * @mbggenerated
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.remark
     *
     * @return the value of product_lib_brand.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.remark
     *
     * @param remark the value for product_lib_brand.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.superiority
     *
     * @return the value of product_lib_brand.superiority
     *
     * @mbggenerated
     */
    public String getSuperiority() {
        return superiority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.superiority
     *
     * @param superiority the value for product_lib_brand.superiority
     *
     * @mbggenerated
     */
    public void setSuperiority(String superiority) {
        this.superiority = superiority == null ? null : superiority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.promotion_plan
     *
     * @return the value of product_lib_brand.promotion_plan
     *
     * @mbggenerated
     */
    public String getPromotionPlan() {
        return promotionPlan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.promotion_plan
     *
     * @param promotionPlan the value for product_lib_brand.promotion_plan
     *
     * @mbggenerated
     */
    public void setPromotionPlan(String promotionPlan) {
        this.promotionPlan = promotionPlan == null ? null : promotionPlan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.image_url
     *
     * @return the value of product_lib_brand.image_url
     *
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.image_url
     *
     * @param imageUrl the value for product_lib_brand.image_url
     *
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.image_big_url
     *
     * @return the value of product_lib_brand.image_big_url
     *
     * @mbggenerated
     */
    public String getImageBigUrl() {
        return imageBigUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.image_big_url
     *
     * @param imageBigUrl the value for product_lib_brand.image_big_url
     *
     * @mbggenerated
     */
    public void setImageBigUrl(String imageBigUrl) {
        this.imageBigUrl = imageBigUrl == null ? null : imageBigUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.package_url
     *
     * @return the value of product_lib_brand.package_url
     *
     * @mbggenerated
     */
    public String getPackageUrl() {
        return packageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.package_url
     *
     * @param packageUrl the value for product_lib_brand.package_url
     *
     * @mbggenerated
     */
    public void setPackageUrl(String packageUrl) {
        this.packageUrl = packageUrl == null ? null : packageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.tag_url
     *
     * @return the value of product_lib_brand.tag_url
     *
     * @mbggenerated
     */
    public String getTagUrl() {
        return tagUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.tag_url
     *
     * @param tagUrl the value for product_lib_brand.tag_url
     *
     * @mbggenerated
     */
    public void setTagUrl(String tagUrl) {
        this.tagUrl = tagUrl == null ? null : tagUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.sort
     *
     * @return the value of product_lib_brand.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.sort
     *
     * @param sort the value for product_lib_brand.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.status
     *
     * @return the value of product_lib_brand.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.status
     *
     * @param status the value for product_lib_brand.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.create_user
     *
     * @return the value of product_lib_brand.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.create_user
     *
     * @param createUser the value for product_lib_brand.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.create_date
     *
     * @return the value of product_lib_brand.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.create_date
     *
     * @param createDate the value for product_lib_brand.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.last_update_user
     *
     * @return the value of product_lib_brand.last_update_user
     *
     * @mbggenerated
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.last_update_user
     *
     * @param lastUpdateUser the value for product_lib_brand.last_update_user
     *
     * @mbggenerated
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.last_update_date
     *
     * @return the value of product_lib_brand.last_update_date
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.last_update_date
     *
     * @param lastUpdateDate the value for product_lib_brand.last_update_date
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_lib_brand.description
     *
     * @return the value of product_lib_brand.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_lib_brand.description
     *
     * @param description the value for product_lib_brand.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}