package com.work.shop.bean.mbproduct;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductSellerGoodsBarcodeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    public ProductSellerGoodsBarcodeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        /**  
         * limit 
         * 
         */ 
        public Criteria limit(int offset, int len) {
            if (len==0 )
              throw new RuntimeException("len is 0");
            addCriterion("limit",offset,len,"null");
            return (Criteria) this;
        }

        /**  
         * top 
         * 
         */ 
        public Criteria limit(int len) {
            if (len==0 )
              throw new RuntimeException("len is 0");
            addCriterion("limit", 0, len, "null");
            return (Criteria) this;
        }

        public Criteria getLimitValue() {
            return (Criteria)criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBarcodeIdIsNull() {
            addCriterion("barcode_id is null");
            return (Criteria) this;
        }

        public Criteria andBarcodeIdIsNotNull() {
            addCriterion("barcode_id is not null");
            return (Criteria) this;
        }

        public Criteria andBarcodeIdEqualTo(Long value) {
            addCriterion("barcode_id =", value, "barcodeId");
            return (Criteria) this;
        }

        public Criteria andBarcodeIdNotEqualTo(Long value) {
            addCriterion("barcode_id <>", value, "barcodeId");
            return (Criteria) this;
        }

        public Criteria andBarcodeIdGreaterThan(Long value) {
            addCriterion("barcode_id >", value, "barcodeId");
            return (Criteria) this;
        }

        public Criteria andBarcodeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("barcode_id >=", value, "barcodeId");
            return (Criteria) this;
        }

        public Criteria andBarcodeIdLessThan(Long value) {
            addCriterion("barcode_id <", value, "barcodeId");
            return (Criteria) this;
        }

        public Criteria andBarcodeIdLessThanOrEqualTo(Long value) {
            addCriterion("barcode_id <=", value, "barcodeId");
            return (Criteria) this;
        }

        public Criteria andBarcodeIdIn(List<Long> values) {
            addCriterion("barcode_id in", values, "barcodeId");
            return (Criteria) this;
        }

        public Criteria andBarcodeIdNotIn(List<Long> values) {
            addCriterion("barcode_id not in", values, "barcodeId");
            return (Criteria) this;
        }

        public Criteria andBarcodeIdBetween(Long value1, Long value2) {
            addCriterion("barcode_id between", value1, value2, "barcodeId");
            return (Criteria) this;
        }

        public Criteria andBarcodeIdNotBetween(Long value1, Long value2) {
            addCriterion("barcode_id not between", value1, value2, "barcodeId");
            return (Criteria) this;
        }

        public Criteria andSellerCodeIsNull() {
            addCriterion("seller_code is null");
            return (Criteria) this;
        }

        public Criteria andSellerCodeIsNotNull() {
            addCriterion("seller_code is not null");
            return (Criteria) this;
        }

        public Criteria andSellerCodeEqualTo(String value) {
            addCriterion("seller_code =", value, "sellerCode");
            return (Criteria) this;
        }

        public Criteria andSellerCodeNotEqualTo(String value) {
            addCriterion("seller_code <>", value, "sellerCode");
            return (Criteria) this;
        }

        public Criteria andSellerCodeGreaterThan(String value) {
            addCriterion("seller_code >", value, "sellerCode");
            return (Criteria) this;
        }

        public Criteria andSellerCodeGreaterThanOrEqualTo(String value) {
            addCriterion("seller_code >=", value, "sellerCode");
            return (Criteria) this;
        }

        public Criteria andSellerCodeLessThan(String value) {
            addCriterion("seller_code <", value, "sellerCode");
            return (Criteria) this;
        }

        public Criteria andSellerCodeLessThanOrEqualTo(String value) {
            addCriterion("seller_code <=", value, "sellerCode");
            return (Criteria) this;
        }

        public Criteria andSellerCodeLike(String value) {
            addCriterion("seller_code like", value, "sellerCode");
            return (Criteria) this;
        }

        public Criteria andSellerCodeNotLike(String value) {
            addCriterion("seller_code not like", value, "sellerCode");
            return (Criteria) this;
        }

        public Criteria andSellerCodeIn(List<String> values) {
            addCriterion("seller_code in", values, "sellerCode");
            return (Criteria) this;
        }

        public Criteria andSellerCodeNotIn(List<String> values) {
            addCriterion("seller_code not in", values, "sellerCode");
            return (Criteria) this;
        }

        public Criteria andSellerCodeBetween(String value1, String value2) {
            addCriterion("seller_code between", value1, value2, "sellerCode");
            return (Criteria) this;
        }

        public Criteria andSellerCodeNotBetween(String value1, String value2) {
            addCriterion("seller_code not between", value1, value2, "sellerCode");
            return (Criteria) this;
        }

        public Criteria andProductSysCodeIsNull() {
            addCriterion("product_sys_code is null");
            return (Criteria) this;
        }

        public Criteria andProductSysCodeIsNotNull() {
            addCriterion("product_sys_code is not null");
            return (Criteria) this;
        }

        public Criteria andProductSysCodeEqualTo(String value) {
            addCriterion("product_sys_code =", value, "productSysCode");
            return (Criteria) this;
        }

        public Criteria andProductSysCodeNotEqualTo(String value) {
            addCriterion("product_sys_code <>", value, "productSysCode");
            return (Criteria) this;
        }

        public Criteria andProductSysCodeGreaterThan(String value) {
            addCriterion("product_sys_code >", value, "productSysCode");
            return (Criteria) this;
        }

        public Criteria andProductSysCodeGreaterThanOrEqualTo(String value) {
            addCriterion("product_sys_code >=", value, "productSysCode");
            return (Criteria) this;
        }

        public Criteria andProductSysCodeLessThan(String value) {
            addCriterion("product_sys_code <", value, "productSysCode");
            return (Criteria) this;
        }

        public Criteria andProductSysCodeLessThanOrEqualTo(String value) {
            addCriterion("product_sys_code <=", value, "productSysCode");
            return (Criteria) this;
        }

        public Criteria andProductSysCodeLike(String value) {
            addCriterion("product_sys_code like", value, "productSysCode");
            return (Criteria) this;
        }

        public Criteria andProductSysCodeNotLike(String value) {
            addCriterion("product_sys_code not like", value, "productSysCode");
            return (Criteria) this;
        }

        public Criteria andProductSysCodeIn(List<String> values) {
            addCriterion("product_sys_code in", values, "productSysCode");
            return (Criteria) this;
        }

        public Criteria andProductSysCodeNotIn(List<String> values) {
            addCriterion("product_sys_code not in", values, "productSysCode");
            return (Criteria) this;
        }

        public Criteria andProductSysCodeBetween(String value1, String value2) {
            addCriterion("product_sys_code between", value1, value2, "productSysCode");
            return (Criteria) this;
        }

        public Criteria andProductSysCodeNotBetween(String value1, String value2) {
            addCriterion("product_sys_code not between", value1, value2, "productSysCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeCodeIsNull() {
            addCriterion("barcode_code is null");
            return (Criteria) this;
        }

        public Criteria andBarcodeCodeIsNotNull() {
            addCriterion("barcode_code is not null");
            return (Criteria) this;
        }

        public Criteria andBarcodeCodeEqualTo(String value) {
            addCriterion("barcode_code =", value, "barcodeCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeCodeNotEqualTo(String value) {
            addCriterion("barcode_code <>", value, "barcodeCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeCodeGreaterThan(String value) {
            addCriterion("barcode_code >", value, "barcodeCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("barcode_code >=", value, "barcodeCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeCodeLessThan(String value) {
            addCriterion("barcode_code <", value, "barcodeCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeCodeLessThanOrEqualTo(String value) {
            addCriterion("barcode_code <=", value, "barcodeCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeCodeLike(String value) {
            addCriterion("barcode_code like", value, "barcodeCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeCodeNotLike(String value) {
            addCriterion("barcode_code not like", value, "barcodeCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeCodeIn(List<String> values) {
            addCriterion("barcode_code in", values, "barcodeCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeCodeNotIn(List<String> values) {
            addCriterion("barcode_code not in", values, "barcodeCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeCodeBetween(String value1, String value2) {
            addCriterion("barcode_code between", value1, value2, "barcodeCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeCodeNotBetween(String value1, String value2) {
            addCriterion("barcode_code not between", value1, value2, "barcodeCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeSysCodeIsNull() {
            addCriterion("barcode_sys_code is null");
            return (Criteria) this;
        }

        public Criteria andBarcodeSysCodeIsNotNull() {
            addCriterion("barcode_sys_code is not null");
            return (Criteria) this;
        }

        public Criteria andBarcodeSysCodeEqualTo(String value) {
            addCriterion("barcode_sys_code =", value, "barcodeSysCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeSysCodeNotEqualTo(String value) {
            addCriterion("barcode_sys_code <>", value, "barcodeSysCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeSysCodeGreaterThan(String value) {
            addCriterion("barcode_sys_code >", value, "barcodeSysCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeSysCodeGreaterThanOrEqualTo(String value) {
            addCriterion("barcode_sys_code >=", value, "barcodeSysCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeSysCodeLessThan(String value) {
            addCriterion("barcode_sys_code <", value, "barcodeSysCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeSysCodeLessThanOrEqualTo(String value) {
            addCriterion("barcode_sys_code <=", value, "barcodeSysCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeSysCodeLike(String value) {
            addCriterion("barcode_sys_code like", value, "barcodeSysCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeSysCodeNotLike(String value) {
            addCriterion("barcode_sys_code not like", value, "barcodeSysCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeSysCodeIn(List<String> values) {
            addCriterion("barcode_sys_code in", values, "barcodeSysCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeSysCodeNotIn(List<String> values) {
            addCriterion("barcode_sys_code not in", values, "barcodeSysCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeSysCodeBetween(String value1, String value2) {
            addCriterion("barcode_sys_code between", value1, value2, "barcodeSysCode");
            return (Criteria) this;
        }

        public Criteria andBarcodeSysCodeNotBetween(String value1, String value2) {
            addCriterion("barcode_sys_code not between", value1, value2, "barcodeSysCode");
            return (Criteria) this;
        }

        public Criteria andIntlCodeIsNull() {
            addCriterion("intl_code is null");
            return (Criteria) this;
        }

        public Criteria andIntlCodeIsNotNull() {
            addCriterion("intl_code is not null");
            return (Criteria) this;
        }

        public Criteria andIntlCodeEqualTo(String value) {
            addCriterion("intl_code =", value, "intlCode");
            return (Criteria) this;
        }

        public Criteria andIntlCodeNotEqualTo(String value) {
            addCriterion("intl_code <>", value, "intlCode");
            return (Criteria) this;
        }

        public Criteria andIntlCodeGreaterThan(String value) {
            addCriterion("intl_code >", value, "intlCode");
            return (Criteria) this;
        }

        public Criteria andIntlCodeGreaterThanOrEqualTo(String value) {
            addCriterion("intl_code >=", value, "intlCode");
            return (Criteria) this;
        }

        public Criteria andIntlCodeLessThan(String value) {
            addCriterion("intl_code <", value, "intlCode");
            return (Criteria) this;
        }

        public Criteria andIntlCodeLessThanOrEqualTo(String value) {
            addCriterion("intl_code <=", value, "intlCode");
            return (Criteria) this;
        }

        public Criteria andIntlCodeLike(String value) {
            addCriterion("intl_code like", value, "intlCode");
            return (Criteria) this;
        }

        public Criteria andIntlCodeNotLike(String value) {
            addCriterion("intl_code not like", value, "intlCode");
            return (Criteria) this;
        }

        public Criteria andIntlCodeIn(List<String> values) {
            addCriterion("intl_code in", values, "intlCode");
            return (Criteria) this;
        }

        public Criteria andIntlCodeNotIn(List<String> values) {
            addCriterion("intl_code not in", values, "intlCode");
            return (Criteria) this;
        }

        public Criteria andIntlCodeBetween(String value1, String value2) {
            addCriterion("intl_code between", value1, value2, "intlCode");
            return (Criteria) this;
        }

        public Criteria andIntlCodeNotBetween(String value1, String value2) {
            addCriterion("intl_code not between", value1, value2, "intlCode");
            return (Criteria) this;
        }

        public Criteria andInnerCodeIsNull() {
            addCriterion("inner_code is null");
            return (Criteria) this;
        }

        public Criteria andInnerCodeIsNotNull() {
            addCriterion("inner_code is not null");
            return (Criteria) this;
        }

        public Criteria andInnerCodeEqualTo(String value) {
            addCriterion("inner_code =", value, "innerCode");
            return (Criteria) this;
        }

        public Criteria andInnerCodeNotEqualTo(String value) {
            addCriterion("inner_code <>", value, "innerCode");
            return (Criteria) this;
        }

        public Criteria andInnerCodeGreaterThan(String value) {
            addCriterion("inner_code >", value, "innerCode");
            return (Criteria) this;
        }

        public Criteria andInnerCodeGreaterThanOrEqualTo(String value) {
            addCriterion("inner_code >=", value, "innerCode");
            return (Criteria) this;
        }

        public Criteria andInnerCodeLessThan(String value) {
            addCriterion("inner_code <", value, "innerCode");
            return (Criteria) this;
        }

        public Criteria andInnerCodeLessThanOrEqualTo(String value) {
            addCriterion("inner_code <=", value, "innerCode");
            return (Criteria) this;
        }

        public Criteria andInnerCodeLike(String value) {
            addCriterion("inner_code like", value, "innerCode");
            return (Criteria) this;
        }

        public Criteria andInnerCodeNotLike(String value) {
            addCriterion("inner_code not like", value, "innerCode");
            return (Criteria) this;
        }

        public Criteria andInnerCodeIn(List<String> values) {
            addCriterion("inner_code in", values, "innerCode");
            return (Criteria) this;
        }

        public Criteria andInnerCodeNotIn(List<String> values) {
            addCriterion("inner_code not in", values, "innerCode");
            return (Criteria) this;
        }

        public Criteria andInnerCodeBetween(String value1, String value2) {
            addCriterion("inner_code between", value1, value2, "innerCode");
            return (Criteria) this;
        }

        public Criteria andInnerCodeNotBetween(String value1, String value2) {
            addCriterion("inner_code not between", value1, value2, "innerCode");
            return (Criteria) this;
        }

        public Criteria andBarcodePriceIsNull() {
            addCriterion("barcode_price is null");
            return (Criteria) this;
        }

        public Criteria andBarcodePriceIsNotNull() {
            addCriterion("barcode_price is not null");
            return (Criteria) this;
        }

        public Criteria andBarcodePriceEqualTo(BigDecimal value) {
            addCriterion("barcode_price =", value, "barcodePrice");
            return (Criteria) this;
        }

        public Criteria andBarcodePriceNotEqualTo(BigDecimal value) {
            addCriterion("barcode_price <>", value, "barcodePrice");
            return (Criteria) this;
        }

        public Criteria andBarcodePriceGreaterThan(BigDecimal value) {
            addCriterion("barcode_price >", value, "barcodePrice");
            return (Criteria) this;
        }

        public Criteria andBarcodePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("barcode_price >=", value, "barcodePrice");
            return (Criteria) this;
        }

        public Criteria andBarcodePriceLessThan(BigDecimal value) {
            addCriterion("barcode_price <", value, "barcodePrice");
            return (Criteria) this;
        }

        public Criteria andBarcodePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("barcode_price <=", value, "barcodePrice");
            return (Criteria) this;
        }

        public Criteria andBarcodePriceIn(List<BigDecimal> values) {
            addCriterion("barcode_price in", values, "barcodePrice");
            return (Criteria) this;
        }

        public Criteria andBarcodePriceNotIn(List<BigDecimal> values) {
            addCriterion("barcode_price not in", values, "barcodePrice");
            return (Criteria) this;
        }

        public Criteria andBarcodePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("barcode_price between", value1, value2, "barcodePrice");
            return (Criteria) this;
        }

        public Criteria andBarcodePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("barcode_price not between", value1, value2, "barcodePrice");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIdIsNull() {
            addCriterion("sale_attr1_key_id is null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIdIsNotNull() {
            addCriterion("sale_attr1_key_id is not null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIdEqualTo(Integer value) {
            addCriterion("sale_attr1_key_id =", value, "saleAttr1KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIdNotEqualTo(Integer value) {
            addCriterion("sale_attr1_key_id <>", value, "saleAttr1KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIdGreaterThan(Integer value) {
            addCriterion("sale_attr1_key_id >", value, "saleAttr1KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sale_attr1_key_id >=", value, "saleAttr1KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIdLessThan(Integer value) {
            addCriterion("sale_attr1_key_id <", value, "saleAttr1KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIdLessThanOrEqualTo(Integer value) {
            addCriterion("sale_attr1_key_id <=", value, "saleAttr1KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIdIn(List<Integer> values) {
            addCriterion("sale_attr1_key_id in", values, "saleAttr1KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIdNotIn(List<Integer> values) {
            addCriterion("sale_attr1_key_id not in", values, "saleAttr1KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIdBetween(Integer value1, Integer value2) {
            addCriterion("sale_attr1_key_id between", value1, value2, "saleAttr1KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sale_attr1_key_id not between", value1, value2, "saleAttr1KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIdIsNull() {
            addCriterion("sale_attr1_value_id is null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIdIsNotNull() {
            addCriterion("sale_attr1_value_id is not null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIdEqualTo(Integer value) {
            addCriterion("sale_attr1_value_id =", value, "saleAttr1ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIdNotEqualTo(Integer value) {
            addCriterion("sale_attr1_value_id <>", value, "saleAttr1ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIdGreaterThan(Integer value) {
            addCriterion("sale_attr1_value_id >", value, "saleAttr1ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sale_attr1_value_id >=", value, "saleAttr1ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIdLessThan(Integer value) {
            addCriterion("sale_attr1_value_id <", value, "saleAttr1ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIdLessThanOrEqualTo(Integer value) {
            addCriterion("sale_attr1_value_id <=", value, "saleAttr1ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIdIn(List<Integer> values) {
            addCriterion("sale_attr1_value_id in", values, "saleAttr1ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIdNotIn(List<Integer> values) {
            addCriterion("sale_attr1_value_id not in", values, "saleAttr1ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIdBetween(Integer value1, Integer value2) {
            addCriterion("sale_attr1_value_id between", value1, value2, "saleAttr1ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sale_attr1_value_id not between", value1, value2, "saleAttr1ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueCodeIsNull() {
            addCriterion("sale_attr1_value_code is null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueCodeIsNotNull() {
            addCriterion("sale_attr1_value_code is not null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueCodeEqualTo(String value) {
            addCriterion("sale_attr1_value_code =", value, "saleAttr1ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueCodeNotEqualTo(String value) {
            addCriterion("sale_attr1_value_code <>", value, "saleAttr1ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueCodeGreaterThan(String value) {
            addCriterion("sale_attr1_value_code >", value, "saleAttr1ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueCodeGreaterThanOrEqualTo(String value) {
            addCriterion("sale_attr1_value_code >=", value, "saleAttr1ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueCodeLessThan(String value) {
            addCriterion("sale_attr1_value_code <", value, "saleAttr1ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueCodeLessThanOrEqualTo(String value) {
            addCriterion("sale_attr1_value_code <=", value, "saleAttr1ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueCodeLike(String value) {
            addCriterion("sale_attr1_value_code like", value, "saleAttr1ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueCodeNotLike(String value) {
            addCriterion("sale_attr1_value_code not like", value, "saleAttr1ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueCodeIn(List<String> values) {
            addCriterion("sale_attr1_value_code in", values, "saleAttr1ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueCodeNotIn(List<String> values) {
            addCriterion("sale_attr1_value_code not in", values, "saleAttr1ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueCodeBetween(String value1, String value2) {
            addCriterion("sale_attr1_value_code between", value1, value2, "saleAttr1ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueCodeNotBetween(String value1, String value2) {
            addCriterion("sale_attr1_value_code not between", value1, value2, "saleAttr1ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIsNull() {
            addCriterion("sale_attr1_key is null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIsNotNull() {
            addCriterion("sale_attr1_key is not null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyEqualTo(String value) {
            addCriterion("sale_attr1_key =", value, "saleAttr1Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyNotEqualTo(String value) {
            addCriterion("sale_attr1_key <>", value, "saleAttr1Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyGreaterThan(String value) {
            addCriterion("sale_attr1_key >", value, "saleAttr1Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyGreaterThanOrEqualTo(String value) {
            addCriterion("sale_attr1_key >=", value, "saleAttr1Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyLessThan(String value) {
            addCriterion("sale_attr1_key <", value, "saleAttr1Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyLessThanOrEqualTo(String value) {
            addCriterion("sale_attr1_key <=", value, "saleAttr1Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyLike(String value) {
            addCriterion("sale_attr1_key like", value, "saleAttr1Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyNotLike(String value) {
            addCriterion("sale_attr1_key not like", value, "saleAttr1Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyIn(List<String> values) {
            addCriterion("sale_attr1_key in", values, "saleAttr1Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyNotIn(List<String> values) {
            addCriterion("sale_attr1_key not in", values, "saleAttr1Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyBetween(String value1, String value2) {
            addCriterion("sale_attr1_key between", value1, value2, "saleAttr1Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1KeyNotBetween(String value1, String value2) {
            addCriterion("sale_attr1_key not between", value1, value2, "saleAttr1Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIsNull() {
            addCriterion("sale_attr1_value is null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIsNotNull() {
            addCriterion("sale_attr1_value is not null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueEqualTo(String value) {
            addCriterion("sale_attr1_value =", value, "saleAttr1Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueNotEqualTo(String value) {
            addCriterion("sale_attr1_value <>", value, "saleAttr1Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueGreaterThan(String value) {
            addCriterion("sale_attr1_value >", value, "saleAttr1Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueGreaterThanOrEqualTo(String value) {
            addCriterion("sale_attr1_value >=", value, "saleAttr1Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueLessThan(String value) {
            addCriterion("sale_attr1_value <", value, "saleAttr1Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueLessThanOrEqualTo(String value) {
            addCriterion("sale_attr1_value <=", value, "saleAttr1Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueLike(String value) {
            addCriterion("sale_attr1_value like", value, "saleAttr1Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueNotLike(String value) {
            addCriterion("sale_attr1_value not like", value, "saleAttr1Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueIn(List<String> values) {
            addCriterion("sale_attr1_value in", values, "saleAttr1Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueNotIn(List<String> values) {
            addCriterion("sale_attr1_value not in", values, "saleAttr1Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueBetween(String value1, String value2) {
            addCriterion("sale_attr1_value between", value1, value2, "saleAttr1Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr1ValueNotBetween(String value1, String value2) {
            addCriterion("sale_attr1_value not between", value1, value2, "saleAttr1Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIdIsNull() {
            addCriterion("sale_attr2_key_id is null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIdIsNotNull() {
            addCriterion("sale_attr2_key_id is not null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIdEqualTo(Integer value) {
            addCriterion("sale_attr2_key_id =", value, "saleAttr2KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIdNotEqualTo(Integer value) {
            addCriterion("sale_attr2_key_id <>", value, "saleAttr2KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIdGreaterThan(Integer value) {
            addCriterion("sale_attr2_key_id >", value, "saleAttr2KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sale_attr2_key_id >=", value, "saleAttr2KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIdLessThan(Integer value) {
            addCriterion("sale_attr2_key_id <", value, "saleAttr2KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIdLessThanOrEqualTo(Integer value) {
            addCriterion("sale_attr2_key_id <=", value, "saleAttr2KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIdIn(List<Integer> values) {
            addCriterion("sale_attr2_key_id in", values, "saleAttr2KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIdNotIn(List<Integer> values) {
            addCriterion("sale_attr2_key_id not in", values, "saleAttr2KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIdBetween(Integer value1, Integer value2) {
            addCriterion("sale_attr2_key_id between", value1, value2, "saleAttr2KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sale_attr2_key_id not between", value1, value2, "saleAttr2KeyId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIdIsNull() {
            addCriterion("sale_attr2_value_id is null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIdIsNotNull() {
            addCriterion("sale_attr2_value_id is not null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIdEqualTo(Integer value) {
            addCriterion("sale_attr2_value_id =", value, "saleAttr2ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIdNotEqualTo(Integer value) {
            addCriterion("sale_attr2_value_id <>", value, "saleAttr2ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIdGreaterThan(Integer value) {
            addCriterion("sale_attr2_value_id >", value, "saleAttr2ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sale_attr2_value_id >=", value, "saleAttr2ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIdLessThan(Integer value) {
            addCriterion("sale_attr2_value_id <", value, "saleAttr2ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIdLessThanOrEqualTo(Integer value) {
            addCriterion("sale_attr2_value_id <=", value, "saleAttr2ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIdIn(List<Integer> values) {
            addCriterion("sale_attr2_value_id in", values, "saleAttr2ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIdNotIn(List<Integer> values) {
            addCriterion("sale_attr2_value_id not in", values, "saleAttr2ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIdBetween(Integer value1, Integer value2) {
            addCriterion("sale_attr2_value_id between", value1, value2, "saleAttr2ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sale_attr2_value_id not between", value1, value2, "saleAttr2ValueId");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueCodeIsNull() {
            addCriterion("sale_attr2_value_code is null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueCodeIsNotNull() {
            addCriterion("sale_attr2_value_code is not null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueCodeEqualTo(String value) {
            addCriterion("sale_attr2_value_code =", value, "saleAttr2ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueCodeNotEqualTo(String value) {
            addCriterion("sale_attr2_value_code <>", value, "saleAttr2ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueCodeGreaterThan(String value) {
            addCriterion("sale_attr2_value_code >", value, "saleAttr2ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueCodeGreaterThanOrEqualTo(String value) {
            addCriterion("sale_attr2_value_code >=", value, "saleAttr2ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueCodeLessThan(String value) {
            addCriterion("sale_attr2_value_code <", value, "saleAttr2ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueCodeLessThanOrEqualTo(String value) {
            addCriterion("sale_attr2_value_code <=", value, "saleAttr2ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueCodeLike(String value) {
            addCriterion("sale_attr2_value_code like", value, "saleAttr2ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueCodeNotLike(String value) {
            addCriterion("sale_attr2_value_code not like", value, "saleAttr2ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueCodeIn(List<String> values) {
            addCriterion("sale_attr2_value_code in", values, "saleAttr2ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueCodeNotIn(List<String> values) {
            addCriterion("sale_attr2_value_code not in", values, "saleAttr2ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueCodeBetween(String value1, String value2) {
            addCriterion("sale_attr2_value_code between", value1, value2, "saleAttr2ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueCodeNotBetween(String value1, String value2) {
            addCriterion("sale_attr2_value_code not between", value1, value2, "saleAttr2ValueCode");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIsNull() {
            addCriterion("sale_attr2_key is null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIsNotNull() {
            addCriterion("sale_attr2_key is not null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyEqualTo(String value) {
            addCriterion("sale_attr2_key =", value, "saleAttr2Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyNotEqualTo(String value) {
            addCriterion("sale_attr2_key <>", value, "saleAttr2Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyGreaterThan(String value) {
            addCriterion("sale_attr2_key >", value, "saleAttr2Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyGreaterThanOrEqualTo(String value) {
            addCriterion("sale_attr2_key >=", value, "saleAttr2Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyLessThan(String value) {
            addCriterion("sale_attr2_key <", value, "saleAttr2Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyLessThanOrEqualTo(String value) {
            addCriterion("sale_attr2_key <=", value, "saleAttr2Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyLike(String value) {
            addCriterion("sale_attr2_key like", value, "saleAttr2Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyNotLike(String value) {
            addCriterion("sale_attr2_key not like", value, "saleAttr2Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyIn(List<String> values) {
            addCriterion("sale_attr2_key in", values, "saleAttr2Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyNotIn(List<String> values) {
            addCriterion("sale_attr2_key not in", values, "saleAttr2Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyBetween(String value1, String value2) {
            addCriterion("sale_attr2_key between", value1, value2, "saleAttr2Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2KeyNotBetween(String value1, String value2) {
            addCriterion("sale_attr2_key not between", value1, value2, "saleAttr2Key");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIsNull() {
            addCriterion("sale_attr2_value is null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIsNotNull() {
            addCriterion("sale_attr2_value is not null");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueEqualTo(String value) {
            addCriterion("sale_attr2_value =", value, "saleAttr2Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueNotEqualTo(String value) {
            addCriterion("sale_attr2_value <>", value, "saleAttr2Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueGreaterThan(String value) {
            addCriterion("sale_attr2_value >", value, "saleAttr2Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueGreaterThanOrEqualTo(String value) {
            addCriterion("sale_attr2_value >=", value, "saleAttr2Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueLessThan(String value) {
            addCriterion("sale_attr2_value <", value, "saleAttr2Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueLessThanOrEqualTo(String value) {
            addCriterion("sale_attr2_value <=", value, "saleAttr2Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueLike(String value) {
            addCriterion("sale_attr2_value like", value, "saleAttr2Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueNotLike(String value) {
            addCriterion("sale_attr2_value not like", value, "saleAttr2Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueIn(List<String> values) {
            addCriterion("sale_attr2_value in", values, "saleAttr2Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueNotIn(List<String> values) {
            addCriterion("sale_attr2_value not in", values, "saleAttr2Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueBetween(String value1, String value2) {
            addCriterion("sale_attr2_value between", value1, value2, "saleAttr2Value");
            return (Criteria) this;
        }

        public Criteria andSaleAttr2ValueNotBetween(String value1, String value2) {
            addCriterion("sale_attr2_value not between", value1, value2, "saleAttr2Value");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIsNull() {
            addCriterion("last_update_user is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIsNotNull() {
            addCriterion("last_update_user is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserEqualTo(String value) {
            addCriterion("last_update_user =", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserNotEqualTo(String value) {
            addCriterion("last_update_user <>", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserGreaterThan(String value) {
            addCriterion("last_update_user >", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("last_update_user >=", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserLessThan(String value) {
            addCriterion("last_update_user <", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("last_update_user <=", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserLike(String value) {
            addCriterion("last_update_user like", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserNotLike(String value) {
            addCriterion("last_update_user not like", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIn(List<String> values) {
            addCriterion("last_update_user in", values, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserNotIn(List<String> values) {
            addCriterion("last_update_user not in", values, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserBetween(String value1, String value2) {
            addCriterion("last_update_user between", value1, value2, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserNotBetween(String value1, String value2) {
            addCriterion("last_update_user not between", value1, value2, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("last_update_date is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("last_update_date is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("last_update_date =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("last_update_date <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("last_update_date >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_date >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("last_update_date <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("last_update_date <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("last_update_date in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("last_update_date not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("last_update_date between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("last_update_date not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastControllerNameIsNull() {
            addCriterion("last_controller_name is null");
            return (Criteria) this;
        }

        public Criteria andLastControllerNameIsNotNull() {
            addCriterion("last_controller_name is not null");
            return (Criteria) this;
        }

        public Criteria andLastControllerNameEqualTo(String value) {
            addCriterion("last_controller_name =", value, "lastControllerName");
            return (Criteria) this;
        }

        public Criteria andLastControllerNameNotEqualTo(String value) {
            addCriterion("last_controller_name <>", value, "lastControllerName");
            return (Criteria) this;
        }

        public Criteria andLastControllerNameGreaterThan(String value) {
            addCriterion("last_controller_name >", value, "lastControllerName");
            return (Criteria) this;
        }

        public Criteria andLastControllerNameGreaterThanOrEqualTo(String value) {
            addCriterion("last_controller_name >=", value, "lastControllerName");
            return (Criteria) this;
        }

        public Criteria andLastControllerNameLessThan(String value) {
            addCriterion("last_controller_name <", value, "lastControllerName");
            return (Criteria) this;
        }

        public Criteria andLastControllerNameLessThanOrEqualTo(String value) {
            addCriterion("last_controller_name <=", value, "lastControllerName");
            return (Criteria) this;
        }

        public Criteria andLastControllerNameLike(String value) {
            addCriterion("last_controller_name like", value, "lastControllerName");
            return (Criteria) this;
        }

        public Criteria andLastControllerNameNotLike(String value) {
            addCriterion("last_controller_name not like", value, "lastControllerName");
            return (Criteria) this;
        }

        public Criteria andLastControllerNameIn(List<String> values) {
            addCriterion("last_controller_name in", values, "lastControllerName");
            return (Criteria) this;
        }

        public Criteria andLastControllerNameNotIn(List<String> values) {
            addCriterion("last_controller_name not in", values, "lastControllerName");
            return (Criteria) this;
        }

        public Criteria andLastControllerNameBetween(String value1, String value2) {
            addCriterion("last_controller_name between", value1, value2, "lastControllerName");
            return (Criteria) this;
        }

        public Criteria andLastControllerNameNotBetween(String value1, String value2) {
            addCriterion("last_controller_name not between", value1, value2, "lastControllerName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean limitValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isLimitValue() {
            return limitValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            if("limit".equals(condition))
              this.limitValue = true;
            else
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}