package com.work.shop.bean.mbproduct;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SapProdClsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    public SapProdClsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        /**  
         * limit 
         * 
         */ 
        public Criteria limit(int offset, int len) {
            if (len==0 )
              throw new RuntimeException("len is 0");
            addCriterion("limit",offset,len,"null");
            return (Criteria) this;
        }

        /**  
         * top 
         * 
         */ 
        public Criteria limit(int len) {
            if (len==0 )
              throw new RuntimeException("len is 0");
            addCriterion("limit", 0, len, "null");
            return (Criteria) this;
        }

        public Criteria getLimitValue() {
            return (Criteria)criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Integer> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Integer> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProdClsNumIsNull() {
            addCriterion("prod_cls_num is null");
            return (Criteria) this;
        }

        public Criteria andProdClsNumIsNotNull() {
            addCriterion("prod_cls_num is not null");
            return (Criteria) this;
        }

        public Criteria andProdClsNumEqualTo(String value) {
            addCriterion("prod_cls_num =", value, "prodClsNum");
            return (Criteria) this;
        }

        public Criteria andProdClsNumNotEqualTo(String value) {
            addCriterion("prod_cls_num <>", value, "prodClsNum");
            return (Criteria) this;
        }

        public Criteria andProdClsNumGreaterThan(String value) {
            addCriterion("prod_cls_num >", value, "prodClsNum");
            return (Criteria) this;
        }

        public Criteria andProdClsNumGreaterThanOrEqualTo(String value) {
            addCriterion("prod_cls_num >=", value, "prodClsNum");
            return (Criteria) this;
        }

        public Criteria andProdClsNumLessThan(String value) {
            addCriterion("prod_cls_num <", value, "prodClsNum");
            return (Criteria) this;
        }

        public Criteria andProdClsNumLessThanOrEqualTo(String value) {
            addCriterion("prod_cls_num <=", value, "prodClsNum");
            return (Criteria) this;
        }

        public Criteria andProdClsNumLike(String value) {
            addCriterion("prod_cls_num like", value, "prodClsNum");
            return (Criteria) this;
        }

        public Criteria andProdClsNumNotLike(String value) {
            addCriterion("prod_cls_num not like", value, "prodClsNum");
            return (Criteria) this;
        }

        public Criteria andProdClsNumIn(List<String> values) {
            addCriterion("prod_cls_num in", values, "prodClsNum");
            return (Criteria) this;
        }

        public Criteria andProdClsNumNotIn(List<String> values) {
            addCriterion("prod_cls_num not in", values, "prodClsNum");
            return (Criteria) this;
        }

        public Criteria andProdClsNumBetween(String value1, String value2) {
            addCriterion("prod_cls_num between", value1, value2, "prodClsNum");
            return (Criteria) this;
        }

        public Criteria andProdClsNumNotBetween(String value1, String value2) {
            addCriterion("prod_cls_num not between", value1, value2, "prodClsNum");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andBrandCodeIsNull() {
            addCriterion("brand_code is null");
            return (Criteria) this;
        }

        public Criteria andBrandCodeIsNotNull() {
            addCriterion("brand_code is not null");
            return (Criteria) this;
        }

        public Criteria andBrandCodeEqualTo(String value) {
            addCriterion("brand_code =", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeNotEqualTo(String value) {
            addCriterion("brand_code <>", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeGreaterThan(String value) {
            addCriterion("brand_code >", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeGreaterThanOrEqualTo(String value) {
            addCriterion("brand_code >=", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeLessThan(String value) {
            addCriterion("brand_code <", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeLessThanOrEqualTo(String value) {
            addCriterion("brand_code <=", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeLike(String value) {
            addCriterion("brand_code like", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeNotLike(String value) {
            addCriterion("brand_code not like", value, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeIn(List<String> values) {
            addCriterion("brand_code in", values, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeNotIn(List<String> values) {
            addCriterion("brand_code not in", values, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeBetween(String value1, String value2) {
            addCriterion("brand_code between", value1, value2, "brandCode");
            return (Criteria) this;
        }

        public Criteria andBrandCodeNotBetween(String value1, String value2) {
            addCriterion("brand_code not between", value1, value2, "brandCode");
            return (Criteria) this;
        }

        public Criteria andReckonTypeIsNull() {
            addCriterion("reckon_type is null");
            return (Criteria) this;
        }

        public Criteria andReckonTypeIsNotNull() {
            addCriterion("reckon_type is not null");
            return (Criteria) this;
        }

        public Criteria andReckonTypeEqualTo(String value) {
            addCriterion("reckon_type =", value, "reckonType");
            return (Criteria) this;
        }

        public Criteria andReckonTypeNotEqualTo(String value) {
            addCriterion("reckon_type <>", value, "reckonType");
            return (Criteria) this;
        }

        public Criteria andReckonTypeGreaterThan(String value) {
            addCriterion("reckon_type >", value, "reckonType");
            return (Criteria) this;
        }

        public Criteria andReckonTypeGreaterThanOrEqualTo(String value) {
            addCriterion("reckon_type >=", value, "reckonType");
            return (Criteria) this;
        }

        public Criteria andReckonTypeLessThan(String value) {
            addCriterion("reckon_type <", value, "reckonType");
            return (Criteria) this;
        }

        public Criteria andReckonTypeLessThanOrEqualTo(String value) {
            addCriterion("reckon_type <=", value, "reckonType");
            return (Criteria) this;
        }

        public Criteria andReckonTypeLike(String value) {
            addCriterion("reckon_type like", value, "reckonType");
            return (Criteria) this;
        }

        public Criteria andReckonTypeNotLike(String value) {
            addCriterion("reckon_type not like", value, "reckonType");
            return (Criteria) this;
        }

        public Criteria andReckonTypeIn(List<String> values) {
            addCriterion("reckon_type in", values, "reckonType");
            return (Criteria) this;
        }

        public Criteria andReckonTypeNotIn(List<String> values) {
            addCriterion("reckon_type not in", values, "reckonType");
            return (Criteria) this;
        }

        public Criteria andReckonTypeBetween(String value1, String value2) {
            addCriterion("reckon_type between", value1, value2, "reckonType");
            return (Criteria) this;
        }

        public Criteria andReckonTypeNotBetween(String value1, String value2) {
            addCriterion("reckon_type not between", value1, value2, "reckonType");
            return (Criteria) this;
        }

        public Criteria andProdTypeIsNull() {
            addCriterion("prod_type is null");
            return (Criteria) this;
        }

        public Criteria andProdTypeIsNotNull() {
            addCriterion("prod_type is not null");
            return (Criteria) this;
        }

        public Criteria andProdTypeEqualTo(String value) {
            addCriterion("prod_type =", value, "prodType");
            return (Criteria) this;
        }

        public Criteria andProdTypeNotEqualTo(String value) {
            addCriterion("prod_type <>", value, "prodType");
            return (Criteria) this;
        }

        public Criteria andProdTypeGreaterThan(String value) {
            addCriterion("prod_type >", value, "prodType");
            return (Criteria) this;
        }

        public Criteria andProdTypeGreaterThanOrEqualTo(String value) {
            addCriterion("prod_type >=", value, "prodType");
            return (Criteria) this;
        }

        public Criteria andProdTypeLessThan(String value) {
            addCriterion("prod_type <", value, "prodType");
            return (Criteria) this;
        }

        public Criteria andProdTypeLessThanOrEqualTo(String value) {
            addCriterion("prod_type <=", value, "prodType");
            return (Criteria) this;
        }

        public Criteria andProdTypeLike(String value) {
            addCriterion("prod_type like", value, "prodType");
            return (Criteria) this;
        }

        public Criteria andProdTypeNotLike(String value) {
            addCriterion("prod_type not like", value, "prodType");
            return (Criteria) this;
        }

        public Criteria andProdTypeIn(List<String> values) {
            addCriterion("prod_type in", values, "prodType");
            return (Criteria) this;
        }

        public Criteria andProdTypeNotIn(List<String> values) {
            addCriterion("prod_type not in", values, "prodType");
            return (Criteria) this;
        }

        public Criteria andProdTypeBetween(String value1, String value2) {
            addCriterion("prod_type between", value1, value2, "prodType");
            return (Criteria) this;
        }

        public Criteria andProdTypeNotBetween(String value1, String value2) {
            addCriterion("prod_type not between", value1, value2, "prodType");
            return (Criteria) this;
        }

        public Criteria andBasicUomIsNull() {
            addCriterion("basic_uom is null");
            return (Criteria) this;
        }

        public Criteria andBasicUomIsNotNull() {
            addCriterion("basic_uom is not null");
            return (Criteria) this;
        }

        public Criteria andBasicUomEqualTo(String value) {
            addCriterion("basic_uom =", value, "basicUom");
            return (Criteria) this;
        }

        public Criteria andBasicUomNotEqualTo(String value) {
            addCriterion("basic_uom <>", value, "basicUom");
            return (Criteria) this;
        }

        public Criteria andBasicUomGreaterThan(String value) {
            addCriterion("basic_uom >", value, "basicUom");
            return (Criteria) this;
        }

        public Criteria andBasicUomGreaterThanOrEqualTo(String value) {
            addCriterion("basic_uom >=", value, "basicUom");
            return (Criteria) this;
        }

        public Criteria andBasicUomLessThan(String value) {
            addCriterion("basic_uom <", value, "basicUom");
            return (Criteria) this;
        }

        public Criteria andBasicUomLessThanOrEqualTo(String value) {
            addCriterion("basic_uom <=", value, "basicUom");
            return (Criteria) this;
        }

        public Criteria andBasicUomLike(String value) {
            addCriterion("basic_uom like", value, "basicUom");
            return (Criteria) this;
        }

        public Criteria andBasicUomNotLike(String value) {
            addCriterion("basic_uom not like", value, "basicUom");
            return (Criteria) this;
        }

        public Criteria andBasicUomIn(List<String> values) {
            addCriterion("basic_uom in", values, "basicUom");
            return (Criteria) this;
        }

        public Criteria andBasicUomNotIn(List<String> values) {
            addCriterion("basic_uom not in", values, "basicUom");
            return (Criteria) this;
        }

        public Criteria andBasicUomBetween(String value1, String value2) {
            addCriterion("basic_uom between", value1, value2, "basicUom");
            return (Criteria) this;
        }

        public Criteria andBasicUomNotBetween(String value1, String value2) {
            addCriterion("basic_uom not between", value1, value2, "basicUom");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("gender like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("gender not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andProdYearIsNull() {
            addCriterion("prod_year is null");
            return (Criteria) this;
        }

        public Criteria andProdYearIsNotNull() {
            addCriterion("prod_year is not null");
            return (Criteria) this;
        }

        public Criteria andProdYearEqualTo(String value) {
            addCriterion("prod_year =", value, "prodYear");
            return (Criteria) this;
        }

        public Criteria andProdYearNotEqualTo(String value) {
            addCriterion("prod_year <>", value, "prodYear");
            return (Criteria) this;
        }

        public Criteria andProdYearGreaterThan(String value) {
            addCriterion("prod_year >", value, "prodYear");
            return (Criteria) this;
        }

        public Criteria andProdYearGreaterThanOrEqualTo(String value) {
            addCriterion("prod_year >=", value, "prodYear");
            return (Criteria) this;
        }

        public Criteria andProdYearLessThan(String value) {
            addCriterion("prod_year <", value, "prodYear");
            return (Criteria) this;
        }

        public Criteria andProdYearLessThanOrEqualTo(String value) {
            addCriterion("prod_year <=", value, "prodYear");
            return (Criteria) this;
        }

        public Criteria andProdYearLike(String value) {
            addCriterion("prod_year like", value, "prodYear");
            return (Criteria) this;
        }

        public Criteria andProdYearNotLike(String value) {
            addCriterion("prod_year not like", value, "prodYear");
            return (Criteria) this;
        }

        public Criteria andProdYearIn(List<String> values) {
            addCriterion("prod_year in", values, "prodYear");
            return (Criteria) this;
        }

        public Criteria andProdYearNotIn(List<String> values) {
            addCriterion("prod_year not in", values, "prodYear");
            return (Criteria) this;
        }

        public Criteria andProdYearBetween(String value1, String value2) {
            addCriterion("prod_year between", value1, value2, "prodYear");
            return (Criteria) this;
        }

        public Criteria andProdYearNotBetween(String value1, String value2) {
            addCriterion("prod_year not between", value1, value2, "prodYear");
            return (Criteria) this;
        }

        public Criteria andProdSeasonIsNull() {
            addCriterion("prod_season is null");
            return (Criteria) this;
        }

        public Criteria andProdSeasonIsNotNull() {
            addCriterion("prod_season is not null");
            return (Criteria) this;
        }

        public Criteria andProdSeasonEqualTo(String value) {
            addCriterion("prod_season =", value, "prodSeason");
            return (Criteria) this;
        }

        public Criteria andProdSeasonNotEqualTo(String value) {
            addCriterion("prod_season <>", value, "prodSeason");
            return (Criteria) this;
        }

        public Criteria andProdSeasonGreaterThan(String value) {
            addCriterion("prod_season >", value, "prodSeason");
            return (Criteria) this;
        }

        public Criteria andProdSeasonGreaterThanOrEqualTo(String value) {
            addCriterion("prod_season >=", value, "prodSeason");
            return (Criteria) this;
        }

        public Criteria andProdSeasonLessThan(String value) {
            addCriterion("prod_season <", value, "prodSeason");
            return (Criteria) this;
        }

        public Criteria andProdSeasonLessThanOrEqualTo(String value) {
            addCriterion("prod_season <=", value, "prodSeason");
            return (Criteria) this;
        }

        public Criteria andProdSeasonLike(String value) {
            addCriterion("prod_season like", value, "prodSeason");
            return (Criteria) this;
        }

        public Criteria andProdSeasonNotLike(String value) {
            addCriterion("prod_season not like", value, "prodSeason");
            return (Criteria) this;
        }

        public Criteria andProdSeasonIn(List<String> values) {
            addCriterion("prod_season in", values, "prodSeason");
            return (Criteria) this;
        }

        public Criteria andProdSeasonNotIn(List<String> values) {
            addCriterion("prod_season not in", values, "prodSeason");
            return (Criteria) this;
        }

        public Criteria andProdSeasonBetween(String value1, String value2) {
            addCriterion("prod_season between", value1, value2, "prodSeason");
            return (Criteria) this;
        }

        public Criteria andProdSeasonNotBetween(String value1, String value2) {
            addCriterion("prod_season not between", value1, value2, "prodSeason");
            return (Criteria) this;
        }

        public Criteria andPlanBatchIsNull() {
            addCriterion("plan_batch is null");
            return (Criteria) this;
        }

        public Criteria andPlanBatchIsNotNull() {
            addCriterion("plan_batch is not null");
            return (Criteria) this;
        }

        public Criteria andPlanBatchEqualTo(String value) {
            addCriterion("plan_batch =", value, "planBatch");
            return (Criteria) this;
        }

        public Criteria andPlanBatchNotEqualTo(String value) {
            addCriterion("plan_batch <>", value, "planBatch");
            return (Criteria) this;
        }

        public Criteria andPlanBatchGreaterThan(String value) {
            addCriterion("plan_batch >", value, "planBatch");
            return (Criteria) this;
        }

        public Criteria andPlanBatchGreaterThanOrEqualTo(String value) {
            addCriterion("plan_batch >=", value, "planBatch");
            return (Criteria) this;
        }

        public Criteria andPlanBatchLessThan(String value) {
            addCriterion("plan_batch <", value, "planBatch");
            return (Criteria) this;
        }

        public Criteria andPlanBatchLessThanOrEqualTo(String value) {
            addCriterion("plan_batch <=", value, "planBatch");
            return (Criteria) this;
        }

        public Criteria andPlanBatchLike(String value) {
            addCriterion("plan_batch like", value, "planBatch");
            return (Criteria) this;
        }

        public Criteria andPlanBatchNotLike(String value) {
            addCriterion("plan_batch not like", value, "planBatch");
            return (Criteria) this;
        }

        public Criteria andPlanBatchIn(List<String> values) {
            addCriterion("plan_batch in", values, "planBatch");
            return (Criteria) this;
        }

        public Criteria andPlanBatchNotIn(List<String> values) {
            addCriterion("plan_batch not in", values, "planBatch");
            return (Criteria) this;
        }

        public Criteria andPlanBatchBetween(String value1, String value2) {
            addCriterion("plan_batch between", value1, value2, "planBatch");
            return (Criteria) this;
        }

        public Criteria andPlanBatchNotBetween(String value1, String value2) {
            addCriterion("plan_batch not between", value1, value2, "planBatch");
            return (Criteria) this;
        }

        public Criteria andEditionBillNumIsNull() {
            addCriterion("edition_bill_num is null");
            return (Criteria) this;
        }

        public Criteria andEditionBillNumIsNotNull() {
            addCriterion("edition_bill_num is not null");
            return (Criteria) this;
        }

        public Criteria andEditionBillNumEqualTo(String value) {
            addCriterion("edition_bill_num =", value, "editionBillNum");
            return (Criteria) this;
        }

        public Criteria andEditionBillNumNotEqualTo(String value) {
            addCriterion("edition_bill_num <>", value, "editionBillNum");
            return (Criteria) this;
        }

        public Criteria andEditionBillNumGreaterThan(String value) {
            addCriterion("edition_bill_num >", value, "editionBillNum");
            return (Criteria) this;
        }

        public Criteria andEditionBillNumGreaterThanOrEqualTo(String value) {
            addCriterion("edition_bill_num >=", value, "editionBillNum");
            return (Criteria) this;
        }

        public Criteria andEditionBillNumLessThan(String value) {
            addCriterion("edition_bill_num <", value, "editionBillNum");
            return (Criteria) this;
        }

        public Criteria andEditionBillNumLessThanOrEqualTo(String value) {
            addCriterion("edition_bill_num <=", value, "editionBillNum");
            return (Criteria) this;
        }

        public Criteria andEditionBillNumLike(String value) {
            addCriterion("edition_bill_num like", value, "editionBillNum");
            return (Criteria) this;
        }

        public Criteria andEditionBillNumNotLike(String value) {
            addCriterion("edition_bill_num not like", value, "editionBillNum");
            return (Criteria) this;
        }

        public Criteria andEditionBillNumIn(List<String> values) {
            addCriterion("edition_bill_num in", values, "editionBillNum");
            return (Criteria) this;
        }

        public Criteria andEditionBillNumNotIn(List<String> values) {
            addCriterion("edition_bill_num not in", values, "editionBillNum");
            return (Criteria) this;
        }

        public Criteria andEditionBillNumBetween(String value1, String value2) {
            addCriterion("edition_bill_num between", value1, value2, "editionBillNum");
            return (Criteria) this;
        }

        public Criteria andEditionBillNumNotBetween(String value1, String value2) {
            addCriterion("edition_bill_num not between", value1, value2, "editionBillNum");
            return (Criteria) this;
        }

        public Criteria andOnBrandPrcIsNull() {
            addCriterion("on_brand_prc is null");
            return (Criteria) this;
        }

        public Criteria andOnBrandPrcIsNotNull() {
            addCriterion("on_brand_prc is not null");
            return (Criteria) this;
        }

        public Criteria andOnBrandPrcEqualTo(BigDecimal value) {
            addCriterion("on_brand_prc =", value, "onBrandPrc");
            return (Criteria) this;
        }

        public Criteria andOnBrandPrcNotEqualTo(BigDecimal value) {
            addCriterion("on_brand_prc <>", value, "onBrandPrc");
            return (Criteria) this;
        }

        public Criteria andOnBrandPrcGreaterThan(BigDecimal value) {
            addCriterion("on_brand_prc >", value, "onBrandPrc");
            return (Criteria) this;
        }

        public Criteria andOnBrandPrcGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("on_brand_prc >=", value, "onBrandPrc");
            return (Criteria) this;
        }

        public Criteria andOnBrandPrcLessThan(BigDecimal value) {
            addCriterion("on_brand_prc <", value, "onBrandPrc");
            return (Criteria) this;
        }

        public Criteria andOnBrandPrcLessThanOrEqualTo(BigDecimal value) {
            addCriterion("on_brand_prc <=", value, "onBrandPrc");
            return (Criteria) this;
        }

        public Criteria andOnBrandPrcIn(List<BigDecimal> values) {
            addCriterion("on_brand_prc in", values, "onBrandPrc");
            return (Criteria) this;
        }

        public Criteria andOnBrandPrcNotIn(List<BigDecimal> values) {
            addCriterion("on_brand_prc not in", values, "onBrandPrc");
            return (Criteria) this;
        }

        public Criteria andOnBrandPrcBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("on_brand_prc between", value1, value2, "onBrandPrc");
            return (Criteria) this;
        }

        public Criteria andOnBrandPrcNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("on_brand_prc not between", value1, value2, "onBrandPrc");
            return (Criteria) this;
        }

        public Criteria andProdStatusIsNull() {
            addCriterion("prod_status is null");
            return (Criteria) this;
        }

        public Criteria andProdStatusIsNotNull() {
            addCriterion("prod_status is not null");
            return (Criteria) this;
        }

        public Criteria andProdStatusEqualTo(String value) {
            addCriterion("prod_status =", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusNotEqualTo(String value) {
            addCriterion("prod_status <>", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusGreaterThan(String value) {
            addCriterion("prod_status >", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusGreaterThanOrEqualTo(String value) {
            addCriterion("prod_status >=", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusLessThan(String value) {
            addCriterion("prod_status <", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusLessThanOrEqualTo(String value) {
            addCriterion("prod_status <=", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusLike(String value) {
            addCriterion("prod_status like", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusNotLike(String value) {
            addCriterion("prod_status not like", value, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusIn(List<String> values) {
            addCriterion("prod_status in", values, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusNotIn(List<String> values) {
            addCriterion("prod_status not in", values, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusBetween(String value1, String value2) {
            addCriterion("prod_status between", value1, value2, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andProdStatusNotBetween(String value1, String value2) {
            addCriterion("prod_status not between", value1, value2, "prodStatus");
            return (Criteria) this;
        }

        public Criteria andSrcBrandIsNull() {
            addCriterion("src_brand is null");
            return (Criteria) this;
        }

        public Criteria andSrcBrandIsNotNull() {
            addCriterion("src_brand is not null");
            return (Criteria) this;
        }

        public Criteria andSrcBrandEqualTo(String value) {
            addCriterion("src_brand =", value, "srcBrand");
            return (Criteria) this;
        }

        public Criteria andSrcBrandNotEqualTo(String value) {
            addCriterion("src_brand <>", value, "srcBrand");
            return (Criteria) this;
        }

        public Criteria andSrcBrandGreaterThan(String value) {
            addCriterion("src_brand >", value, "srcBrand");
            return (Criteria) this;
        }

        public Criteria andSrcBrandGreaterThanOrEqualTo(String value) {
            addCriterion("src_brand >=", value, "srcBrand");
            return (Criteria) this;
        }

        public Criteria andSrcBrandLessThan(String value) {
            addCriterion("src_brand <", value, "srcBrand");
            return (Criteria) this;
        }

        public Criteria andSrcBrandLessThanOrEqualTo(String value) {
            addCriterion("src_brand <=", value, "srcBrand");
            return (Criteria) this;
        }

        public Criteria andSrcBrandLike(String value) {
            addCriterion("src_brand like", value, "srcBrand");
            return (Criteria) this;
        }

        public Criteria andSrcBrandNotLike(String value) {
            addCriterion("src_brand not like", value, "srcBrand");
            return (Criteria) this;
        }

        public Criteria andSrcBrandIn(List<String> values) {
            addCriterion("src_brand in", values, "srcBrand");
            return (Criteria) this;
        }

        public Criteria andSrcBrandNotIn(List<String> values) {
            addCriterion("src_brand not in", values, "srcBrand");
            return (Criteria) this;
        }

        public Criteria andSrcBrandBetween(String value1, String value2) {
            addCriterion("src_brand between", value1, value2, "srcBrand");
            return (Criteria) this;
        }

        public Criteria andSrcBrandNotBetween(String value1, String value2) {
            addCriterion("src_brand not between", value1, value2, "srcBrand");
            return (Criteria) this;
        }

        public Criteria andPurModeIsNull() {
            addCriterion("pur_mode is null");
            return (Criteria) this;
        }

        public Criteria andPurModeIsNotNull() {
            addCriterion("pur_mode is not null");
            return (Criteria) this;
        }

        public Criteria andPurModeEqualTo(String value) {
            addCriterion("pur_mode =", value, "purMode");
            return (Criteria) this;
        }

        public Criteria andPurModeNotEqualTo(String value) {
            addCriterion("pur_mode <>", value, "purMode");
            return (Criteria) this;
        }

        public Criteria andPurModeGreaterThan(String value) {
            addCriterion("pur_mode >", value, "purMode");
            return (Criteria) this;
        }

        public Criteria andPurModeGreaterThanOrEqualTo(String value) {
            addCriterion("pur_mode >=", value, "purMode");
            return (Criteria) this;
        }

        public Criteria andPurModeLessThan(String value) {
            addCriterion("pur_mode <", value, "purMode");
            return (Criteria) this;
        }

        public Criteria andPurModeLessThanOrEqualTo(String value) {
            addCriterion("pur_mode <=", value, "purMode");
            return (Criteria) this;
        }

        public Criteria andPurModeLike(String value) {
            addCriterion("pur_mode like", value, "purMode");
            return (Criteria) this;
        }

        public Criteria andPurModeNotLike(String value) {
            addCriterion("pur_mode not like", value, "purMode");
            return (Criteria) this;
        }

        public Criteria andPurModeIn(List<String> values) {
            addCriterion("pur_mode in", values, "purMode");
            return (Criteria) this;
        }

        public Criteria andPurModeNotIn(List<String> values) {
            addCriterion("pur_mode not in", values, "purMode");
            return (Criteria) this;
        }

        public Criteria andPurModeBetween(String value1, String value2) {
            addCriterion("pur_mode between", value1, value2, "purMode");
            return (Criteria) this;
        }

        public Criteria andPurModeNotBetween(String value1, String value2) {
            addCriterion("pur_mode not between", value1, value2, "purMode");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andSeriesIsNull() {
            addCriterion("series is null");
            return (Criteria) this;
        }

        public Criteria andSeriesIsNotNull() {
            addCriterion("series is not null");
            return (Criteria) this;
        }

        public Criteria andSeriesEqualTo(String value) {
            addCriterion("series =", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesNotEqualTo(String value) {
            addCriterion("series <>", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesGreaterThan(String value) {
            addCriterion("series >", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesGreaterThanOrEqualTo(String value) {
            addCriterion("series >=", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesLessThan(String value) {
            addCriterion("series <", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesLessThanOrEqualTo(String value) {
            addCriterion("series <=", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesLike(String value) {
            addCriterion("series like", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesNotLike(String value) {
            addCriterion("series not like", value, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesIn(List<String> values) {
            addCriterion("series in", values, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesNotIn(List<String> values) {
            addCriterion("series not in", values, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesBetween(String value1, String value2) {
            addCriterion("series between", value1, value2, "series");
            return (Criteria) this;
        }

        public Criteria andSeriesNotBetween(String value1, String value2) {
            addCriterion("series not between", value1, value2, "series");
            return (Criteria) this;
        }

        public Criteria andProdThemeIsNull() {
            addCriterion("prod_theme is null");
            return (Criteria) this;
        }

        public Criteria andProdThemeIsNotNull() {
            addCriterion("prod_theme is not null");
            return (Criteria) this;
        }

        public Criteria andProdThemeEqualTo(String value) {
            addCriterion("prod_theme =", value, "prodTheme");
            return (Criteria) this;
        }

        public Criteria andProdThemeNotEqualTo(String value) {
            addCriterion("prod_theme <>", value, "prodTheme");
            return (Criteria) this;
        }

        public Criteria andProdThemeGreaterThan(String value) {
            addCriterion("prod_theme >", value, "prodTheme");
            return (Criteria) this;
        }

        public Criteria andProdThemeGreaterThanOrEqualTo(String value) {
            addCriterion("prod_theme >=", value, "prodTheme");
            return (Criteria) this;
        }

        public Criteria andProdThemeLessThan(String value) {
            addCriterion("prod_theme <", value, "prodTheme");
            return (Criteria) this;
        }

        public Criteria andProdThemeLessThanOrEqualTo(String value) {
            addCriterion("prod_theme <=", value, "prodTheme");
            return (Criteria) this;
        }

        public Criteria andProdThemeLike(String value) {
            addCriterion("prod_theme like", value, "prodTheme");
            return (Criteria) this;
        }

        public Criteria andProdThemeNotLike(String value) {
            addCriterion("prod_theme not like", value, "prodTheme");
            return (Criteria) this;
        }

        public Criteria andProdThemeIn(List<String> values) {
            addCriterion("prod_theme in", values, "prodTheme");
            return (Criteria) this;
        }

        public Criteria andProdThemeNotIn(List<String> values) {
            addCriterion("prod_theme not in", values, "prodTheme");
            return (Criteria) this;
        }

        public Criteria andProdThemeBetween(String value1, String value2) {
            addCriterion("prod_theme between", value1, value2, "prodTheme");
            return (Criteria) this;
        }

        public Criteria andProdThemeNotBetween(String value1, String value2) {
            addCriterion("prod_theme not between", value1, value2, "prodTheme");
            return (Criteria) this;
        }

        public Criteria andProdGroupIsNull() {
            addCriterion("prod_group is null");
            return (Criteria) this;
        }

        public Criteria andProdGroupIsNotNull() {
            addCriterion("prod_group is not null");
            return (Criteria) this;
        }

        public Criteria andProdGroupEqualTo(String value) {
            addCriterion("prod_group =", value, "prodGroup");
            return (Criteria) this;
        }

        public Criteria andProdGroupNotEqualTo(String value) {
            addCriterion("prod_group <>", value, "prodGroup");
            return (Criteria) this;
        }

        public Criteria andProdGroupGreaterThan(String value) {
            addCriterion("prod_group >", value, "prodGroup");
            return (Criteria) this;
        }

        public Criteria andProdGroupGreaterThanOrEqualTo(String value) {
            addCriterion("prod_group >=", value, "prodGroup");
            return (Criteria) this;
        }

        public Criteria andProdGroupLessThan(String value) {
            addCriterion("prod_group <", value, "prodGroup");
            return (Criteria) this;
        }

        public Criteria andProdGroupLessThanOrEqualTo(String value) {
            addCriterion("prod_group <=", value, "prodGroup");
            return (Criteria) this;
        }

        public Criteria andProdGroupLike(String value) {
            addCriterion("prod_group like", value, "prodGroup");
            return (Criteria) this;
        }

        public Criteria andProdGroupNotLike(String value) {
            addCriterion("prod_group not like", value, "prodGroup");
            return (Criteria) this;
        }

        public Criteria andProdGroupIn(List<String> values) {
            addCriterion("prod_group in", values, "prodGroup");
            return (Criteria) this;
        }

        public Criteria andProdGroupNotIn(List<String> values) {
            addCriterion("prod_group not in", values, "prodGroup");
            return (Criteria) this;
        }

        public Criteria andProdGroupBetween(String value1, String value2) {
            addCriterion("prod_group between", value1, value2, "prodGroup");
            return (Criteria) this;
        }

        public Criteria andProdGroupNotBetween(String value1, String value2) {
            addCriterion("prod_group not between", value1, value2, "prodGroup");
            return (Criteria) this;
        }

        public Criteria andProdSubGroupIsNull() {
            addCriterion("prod_sub_group is null");
            return (Criteria) this;
        }

        public Criteria andProdSubGroupIsNotNull() {
            addCriterion("prod_sub_group is not null");
            return (Criteria) this;
        }

        public Criteria andProdSubGroupEqualTo(String value) {
            addCriterion("prod_sub_group =", value, "prodSubGroup");
            return (Criteria) this;
        }

        public Criteria andProdSubGroupNotEqualTo(String value) {
            addCriterion("prod_sub_group <>", value, "prodSubGroup");
            return (Criteria) this;
        }

        public Criteria andProdSubGroupGreaterThan(String value) {
            addCriterion("prod_sub_group >", value, "prodSubGroup");
            return (Criteria) this;
        }

        public Criteria andProdSubGroupGreaterThanOrEqualTo(String value) {
            addCriterion("prod_sub_group >=", value, "prodSubGroup");
            return (Criteria) this;
        }

        public Criteria andProdSubGroupLessThan(String value) {
            addCriterion("prod_sub_group <", value, "prodSubGroup");
            return (Criteria) this;
        }

        public Criteria andProdSubGroupLessThanOrEqualTo(String value) {
            addCriterion("prod_sub_group <=", value, "prodSubGroup");
            return (Criteria) this;
        }

        public Criteria andProdSubGroupLike(String value) {
            addCriterion("prod_sub_group like", value, "prodSubGroup");
            return (Criteria) this;
        }

        public Criteria andProdSubGroupNotLike(String value) {
            addCriterion("prod_sub_group not like", value, "prodSubGroup");
            return (Criteria) this;
        }

        public Criteria andProdSubGroupIn(List<String> values) {
            addCriterion("prod_sub_group in", values, "prodSubGroup");
            return (Criteria) this;
        }

        public Criteria andProdSubGroupNotIn(List<String> values) {
            addCriterion("prod_sub_group not in", values, "prodSubGroup");
            return (Criteria) this;
        }

        public Criteria andProdSubGroupBetween(String value1, String value2) {
            addCriterion("prod_sub_group between", value1, value2, "prodSubGroup");
            return (Criteria) this;
        }

        public Criteria andProdSubGroupNotBetween(String value1, String value2) {
            addCriterion("prod_sub_group not between", value1, value2, "prodSubGroup");
            return (Criteria) this;
        }

        public Criteria andProdPartmIsNull() {
            addCriterion("prod_partm is null");
            return (Criteria) this;
        }

        public Criteria andProdPartmIsNotNull() {
            addCriterion("prod_partm is not null");
            return (Criteria) this;
        }

        public Criteria andProdPartmEqualTo(String value) {
            addCriterion("prod_partm =", value, "prodPartm");
            return (Criteria) this;
        }

        public Criteria andProdPartmNotEqualTo(String value) {
            addCriterion("prod_partm <>", value, "prodPartm");
            return (Criteria) this;
        }

        public Criteria andProdPartmGreaterThan(String value) {
            addCriterion("prod_partm >", value, "prodPartm");
            return (Criteria) this;
        }

        public Criteria andProdPartmGreaterThanOrEqualTo(String value) {
            addCriterion("prod_partm >=", value, "prodPartm");
            return (Criteria) this;
        }

        public Criteria andProdPartmLessThan(String value) {
            addCriterion("prod_partm <", value, "prodPartm");
            return (Criteria) this;
        }

        public Criteria andProdPartmLessThanOrEqualTo(String value) {
            addCriterion("prod_partm <=", value, "prodPartm");
            return (Criteria) this;
        }

        public Criteria andProdPartmLike(String value) {
            addCriterion("prod_partm like", value, "prodPartm");
            return (Criteria) this;
        }

        public Criteria andProdPartmNotLike(String value) {
            addCriterion("prod_partm not like", value, "prodPartm");
            return (Criteria) this;
        }

        public Criteria andProdPartmIn(List<String> values) {
            addCriterion("prod_partm in", values, "prodPartm");
            return (Criteria) this;
        }

        public Criteria andProdPartmNotIn(List<String> values) {
            addCriterion("prod_partm not in", values, "prodPartm");
            return (Criteria) this;
        }

        public Criteria andProdPartmBetween(String value1, String value2) {
            addCriterion("prod_partm between", value1, value2, "prodPartm");
            return (Criteria) this;
        }

        public Criteria andProdPartmNotBetween(String value1, String value2) {
            addCriterion("prod_partm not between", value1, value2, "prodPartm");
            return (Criteria) this;
        }

        public Criteria andProdSortsIsNull() {
            addCriterion("prod_sorts is null");
            return (Criteria) this;
        }

        public Criteria andProdSortsIsNotNull() {
            addCriterion("prod_sorts is not null");
            return (Criteria) this;
        }

        public Criteria andProdSortsEqualTo(String value) {
            addCriterion("prod_sorts =", value, "prodSorts");
            return (Criteria) this;
        }

        public Criteria andProdSortsNotEqualTo(String value) {
            addCriterion("prod_sorts <>", value, "prodSorts");
            return (Criteria) this;
        }

        public Criteria andProdSortsGreaterThan(String value) {
            addCriterion("prod_sorts >", value, "prodSorts");
            return (Criteria) this;
        }

        public Criteria andProdSortsGreaterThanOrEqualTo(String value) {
            addCriterion("prod_sorts >=", value, "prodSorts");
            return (Criteria) this;
        }

        public Criteria andProdSortsLessThan(String value) {
            addCriterion("prod_sorts <", value, "prodSorts");
            return (Criteria) this;
        }

        public Criteria andProdSortsLessThanOrEqualTo(String value) {
            addCriterion("prod_sorts <=", value, "prodSorts");
            return (Criteria) this;
        }

        public Criteria andProdSortsLike(String value) {
            addCriterion("prod_sorts like", value, "prodSorts");
            return (Criteria) this;
        }

        public Criteria andProdSortsNotLike(String value) {
            addCriterion("prod_sorts not like", value, "prodSorts");
            return (Criteria) this;
        }

        public Criteria andProdSortsIn(List<String> values) {
            addCriterion("prod_sorts in", values, "prodSorts");
            return (Criteria) this;
        }

        public Criteria andProdSortsNotIn(List<String> values) {
            addCriterion("prod_sorts not in", values, "prodSorts");
            return (Criteria) this;
        }

        public Criteria andProdSortsBetween(String value1, String value2) {
            addCriterion("prod_sorts between", value1, value2, "prodSorts");
            return (Criteria) this;
        }

        public Criteria andProdSortsNotBetween(String value1, String value2) {
            addCriterion("prod_sorts not between", value1, value2, "prodSorts");
            return (Criteria) this;
        }

        public Criteria andAdvantageIsNull() {
            addCriterion("advantage is null");
            return (Criteria) this;
        }

        public Criteria andAdvantageIsNotNull() {
            addCriterion("advantage is not null");
            return (Criteria) this;
        }

        public Criteria andAdvantageEqualTo(String value) {
            addCriterion("advantage =", value, "advantage");
            return (Criteria) this;
        }

        public Criteria andAdvantageNotEqualTo(String value) {
            addCriterion("advantage <>", value, "advantage");
            return (Criteria) this;
        }

        public Criteria andAdvantageGreaterThan(String value) {
            addCriterion("advantage >", value, "advantage");
            return (Criteria) this;
        }

        public Criteria andAdvantageGreaterThanOrEqualTo(String value) {
            addCriterion("advantage >=", value, "advantage");
            return (Criteria) this;
        }

        public Criteria andAdvantageLessThan(String value) {
            addCriterion("advantage <", value, "advantage");
            return (Criteria) this;
        }

        public Criteria andAdvantageLessThanOrEqualTo(String value) {
            addCriterion("advantage <=", value, "advantage");
            return (Criteria) this;
        }

        public Criteria andAdvantageLike(String value) {
            addCriterion("advantage like", value, "advantage");
            return (Criteria) this;
        }

        public Criteria andAdvantageNotLike(String value) {
            addCriterion("advantage not like", value, "advantage");
            return (Criteria) this;
        }

        public Criteria andAdvantageIn(List<String> values) {
            addCriterion("advantage in", values, "advantage");
            return (Criteria) this;
        }

        public Criteria andAdvantageNotIn(List<String> values) {
            addCriterion("advantage not in", values, "advantage");
            return (Criteria) this;
        }

        public Criteria andAdvantageBetween(String value1, String value2) {
            addCriterion("advantage between", value1, value2, "advantage");
            return (Criteria) this;
        }

        public Criteria andAdvantageNotBetween(String value1, String value2) {
            addCriterion("advantage not between", value1, value2, "advantage");
            return (Criteria) this;
        }

        public Criteria andSaleDateIsNull() {
            addCriterion("sale_date is null");
            return (Criteria) this;
        }

        public Criteria andSaleDateIsNotNull() {
            addCriterion("sale_date is not null");
            return (Criteria) this;
        }

        public Criteria andSaleDateEqualTo(String value) {
            addCriterion("sale_date =", value, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateNotEqualTo(String value) {
            addCriterion("sale_date <>", value, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateGreaterThan(String value) {
            addCriterion("sale_date >", value, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateGreaterThanOrEqualTo(String value) {
            addCriterion("sale_date >=", value, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateLessThan(String value) {
            addCriterion("sale_date <", value, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateLessThanOrEqualTo(String value) {
            addCriterion("sale_date <=", value, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateLike(String value) {
            addCriterion("sale_date like", value, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateNotLike(String value) {
            addCriterion("sale_date not like", value, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateIn(List<String> values) {
            addCriterion("sale_date in", values, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateNotIn(List<String> values) {
            addCriterion("sale_date not in", values, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateBetween(String value1, String value2) {
            addCriterion("sale_date between", value1, value2, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSaleDateNotBetween(String value1, String value2) {
            addCriterion("sale_date not between", value1, value2, "saleDate");
            return (Criteria) this;
        }

        public Criteria andSpecCharValueIsNull() {
            addCriterion("spec_char_value is null");
            return (Criteria) this;
        }

        public Criteria andSpecCharValueIsNotNull() {
            addCriterion("spec_char_value is not null");
            return (Criteria) this;
        }

        public Criteria andSpecCharValueEqualTo(String value) {
            addCriterion("spec_char_value =", value, "specCharValue");
            return (Criteria) this;
        }

        public Criteria andSpecCharValueNotEqualTo(String value) {
            addCriterion("spec_char_value <>", value, "specCharValue");
            return (Criteria) this;
        }

        public Criteria andSpecCharValueGreaterThan(String value) {
            addCriterion("spec_char_value >", value, "specCharValue");
            return (Criteria) this;
        }

        public Criteria andSpecCharValueGreaterThanOrEqualTo(String value) {
            addCriterion("spec_char_value >=", value, "specCharValue");
            return (Criteria) this;
        }

        public Criteria andSpecCharValueLessThan(String value) {
            addCriterion("spec_char_value <", value, "specCharValue");
            return (Criteria) this;
        }

        public Criteria andSpecCharValueLessThanOrEqualTo(String value) {
            addCriterion("spec_char_value <=", value, "specCharValue");
            return (Criteria) this;
        }

        public Criteria andSpecCharValueLike(String value) {
            addCriterion("spec_char_value like", value, "specCharValue");
            return (Criteria) this;
        }

        public Criteria andSpecCharValueNotLike(String value) {
            addCriterion("spec_char_value not like", value, "specCharValue");
            return (Criteria) this;
        }

        public Criteria andSpecCharValueIn(List<String> values) {
            addCriterion("spec_char_value in", values, "specCharValue");
            return (Criteria) this;
        }

        public Criteria andSpecCharValueNotIn(List<String> values) {
            addCriterion("spec_char_value not in", values, "specCharValue");
            return (Criteria) this;
        }

        public Criteria andSpecCharValueBetween(String value1, String value2) {
            addCriterion("spec_char_value between", value1, value2, "specCharValue");
            return (Criteria) this;
        }

        public Criteria andSpecCharValueNotBetween(String value1, String value2) {
            addCriterion("spec_char_value not between", value1, value2, "specCharValue");
            return (Criteria) this;
        }

        public Criteria andSpecCharDescIsNull() {
            addCriterion("spec_char_desc is null");
            return (Criteria) this;
        }

        public Criteria andSpecCharDescIsNotNull() {
            addCriterion("spec_char_desc is not null");
            return (Criteria) this;
        }

        public Criteria andSpecCharDescEqualTo(String value) {
            addCriterion("spec_char_desc =", value, "specCharDesc");
            return (Criteria) this;
        }

        public Criteria andSpecCharDescNotEqualTo(String value) {
            addCriterion("spec_char_desc <>", value, "specCharDesc");
            return (Criteria) this;
        }

        public Criteria andSpecCharDescGreaterThan(String value) {
            addCriterion("spec_char_desc >", value, "specCharDesc");
            return (Criteria) this;
        }

        public Criteria andSpecCharDescGreaterThanOrEqualTo(String value) {
            addCriterion("spec_char_desc >=", value, "specCharDesc");
            return (Criteria) this;
        }

        public Criteria andSpecCharDescLessThan(String value) {
            addCriterion("spec_char_desc <", value, "specCharDesc");
            return (Criteria) this;
        }

        public Criteria andSpecCharDescLessThanOrEqualTo(String value) {
            addCriterion("spec_char_desc <=", value, "specCharDesc");
            return (Criteria) this;
        }

        public Criteria andSpecCharDescLike(String value) {
            addCriterion("spec_char_desc like", value, "specCharDesc");
            return (Criteria) this;
        }

        public Criteria andSpecCharDescNotLike(String value) {
            addCriterion("spec_char_desc not like", value, "specCharDesc");
            return (Criteria) this;
        }

        public Criteria andSpecCharDescIn(List<String> values) {
            addCriterion("spec_char_desc in", values, "specCharDesc");
            return (Criteria) this;
        }

        public Criteria andSpecCharDescNotIn(List<String> values) {
            addCriterion("spec_char_desc not in", values, "specCharDesc");
            return (Criteria) this;
        }

        public Criteria andSpecCharDescBetween(String value1, String value2) {
            addCriterion("spec_char_desc between", value1, value2, "specCharDesc");
            return (Criteria) this;
        }

        public Criteria andSpecCharDescNotBetween(String value1, String value2) {
            addCriterion("spec_char_desc not between", value1, value2, "specCharDesc");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andPlatformGenStatusIsNull() {
            addCriterion("platform_gen_status is null");
            return (Criteria) this;
        }

        public Criteria andPlatformGenStatusIsNotNull() {
            addCriterion("platform_gen_status is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformGenStatusEqualTo(String value) {
            addCriterion("platform_gen_status =", value, "platformGenStatus");
            return (Criteria) this;
        }

        public Criteria andPlatformGenStatusNotEqualTo(String value) {
            addCriterion("platform_gen_status <>", value, "platformGenStatus");
            return (Criteria) this;
        }

        public Criteria andPlatformGenStatusGreaterThan(String value) {
            addCriterion("platform_gen_status >", value, "platformGenStatus");
            return (Criteria) this;
        }

        public Criteria andPlatformGenStatusGreaterThanOrEqualTo(String value) {
            addCriterion("platform_gen_status >=", value, "platformGenStatus");
            return (Criteria) this;
        }

        public Criteria andPlatformGenStatusLessThan(String value) {
            addCriterion("platform_gen_status <", value, "platformGenStatus");
            return (Criteria) this;
        }

        public Criteria andPlatformGenStatusLessThanOrEqualTo(String value) {
            addCriterion("platform_gen_status <=", value, "platformGenStatus");
            return (Criteria) this;
        }

        public Criteria andPlatformGenStatusLike(String value) {
            addCriterion("platform_gen_status like", value, "platformGenStatus");
            return (Criteria) this;
        }

        public Criteria andPlatformGenStatusNotLike(String value) {
            addCriterion("platform_gen_status not like", value, "platformGenStatus");
            return (Criteria) this;
        }

        public Criteria andPlatformGenStatusIn(List<String> values) {
            addCriterion("platform_gen_status in", values, "platformGenStatus");
            return (Criteria) this;
        }

        public Criteria andPlatformGenStatusNotIn(List<String> values) {
            addCriterion("platform_gen_status not in", values, "platformGenStatus");
            return (Criteria) this;
        }

        public Criteria andPlatformGenStatusBetween(String value1, String value2) {
            addCriterion("platform_gen_status between", value1, value2, "platformGenStatus");
            return (Criteria) this;
        }

        public Criteria andPlatformGenStatusNotBetween(String value1, String value2) {
            addCriterion("platform_gen_status not between", value1, value2, "platformGenStatus");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIsNull() {
            addCriterion("last_update_user is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIsNotNull() {
            addCriterion("last_update_user is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserEqualTo(String value) {
            addCriterion("last_update_user =", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserNotEqualTo(String value) {
            addCriterion("last_update_user <>", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserGreaterThan(String value) {
            addCriterion("last_update_user >", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("last_update_user >=", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserLessThan(String value) {
            addCriterion("last_update_user <", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("last_update_user <=", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserLike(String value) {
            addCriterion("last_update_user like", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserNotLike(String value) {
            addCriterion("last_update_user not like", value, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserIn(List<String> values) {
            addCriterion("last_update_user in", values, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserNotIn(List<String> values) {
            addCriterion("last_update_user not in", values, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserBetween(String value1, String value2) {
            addCriterion("last_update_user between", value1, value2, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateUserNotBetween(String value1, String value2) {
            addCriterion("last_update_user not between", value1, value2, "lastUpdateUser");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("last_update_date is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("last_update_date is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("last_update_date =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("last_update_date <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("last_update_date >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_date >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("last_update_date <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("last_update_date <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("last_update_date in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("last_update_date not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("last_update_date between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("last_update_date not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sap_prod_cls
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean limitValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isLimitValue() {
            return limitValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            if("limit".equals(condition))
              this.limitValue = true;
            else
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}