package com.work.shop.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChannelVdepotInventoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    public ChannelVdepotInventoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        /**  
         * limit 
         * 
         */ 
        public Criteria limit(int offset, int len) {
            if (len==0 )
              throw new RuntimeException("len is 0");
            addCriterion("limit",offset,len,"null");
            return (Criteria) this;
        }

        /**  
         * top 
         * 
         */ 
        public Criteria limit(int len) {
            if (len==0 )
              throw new RuntimeException("len is 0");
            addCriterion("limit", 0, len, "null");
            return (Criteria) this;
        }

        public Criteria getLimitValue() {
            return (Criteria)criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVdepotCodeIsNull() {
            addCriterion("vdepot_code is null");
            return (Criteria) this;
        }

        public Criteria andVdepotCodeIsNotNull() {
            addCriterion("vdepot_code is not null");
            return (Criteria) this;
        }

        public Criteria andVdepotCodeEqualTo(String value) {
            addCriterion("vdepot_code =", value, "vdepotCode");
            return (Criteria) this;
        }

        public Criteria andVdepotCodeNotEqualTo(String value) {
            addCriterion("vdepot_code <>", value, "vdepotCode");
            return (Criteria) this;
        }

        public Criteria andVdepotCodeGreaterThan(String value) {
            addCriterion("vdepot_code >", value, "vdepotCode");
            return (Criteria) this;
        }

        public Criteria andVdepotCodeGreaterThanOrEqualTo(String value) {
            addCriterion("vdepot_code >=", value, "vdepotCode");
            return (Criteria) this;
        }

        public Criteria andVdepotCodeLessThan(String value) {
            addCriterion("vdepot_code <", value, "vdepotCode");
            return (Criteria) this;
        }

        public Criteria andVdepotCodeLessThanOrEqualTo(String value) {
            addCriterion("vdepot_code <=", value, "vdepotCode");
            return (Criteria) this;
        }

        public Criteria andVdepotCodeLike(String value) {
            addCriterion("vdepot_code like", value, "vdepotCode");
            return (Criteria) this;
        }

        public Criteria andVdepotCodeNotLike(String value) {
            addCriterion("vdepot_code not like", value, "vdepotCode");
            return (Criteria) this;
        }

        public Criteria andVdepotCodeIn(List<String> values) {
            addCriterion("vdepot_code in", values, "vdepotCode");
            return (Criteria) this;
        }

        public Criteria andVdepotCodeNotIn(List<String> values) {
            addCriterion("vdepot_code not in", values, "vdepotCode");
            return (Criteria) this;
        }

        public Criteria andVdepotCodeBetween(String value1, String value2) {
            addCriterion("vdepot_code between", value1, value2, "vdepotCode");
            return (Criteria) this;
        }

        public Criteria andVdepotCodeNotBetween(String value1, String value2) {
            addCriterion("vdepot_code not between", value1, value2, "vdepotCode");
            return (Criteria) this;
        }

        public Criteria andGoodsSnIsNull() {
            addCriterion("goods_sn is null");
            return (Criteria) this;
        }

        public Criteria andGoodsSnIsNotNull() {
            addCriterion("goods_sn is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsSnEqualTo(String value) {
            addCriterion("goods_sn =", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnNotEqualTo(String value) {
            addCriterion("goods_sn <>", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnGreaterThan(String value) {
            addCriterion("goods_sn >", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnGreaterThanOrEqualTo(String value) {
            addCriterion("goods_sn >=", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnLessThan(String value) {
            addCriterion("goods_sn <", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnLessThanOrEqualTo(String value) {
            addCriterion("goods_sn <=", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnLike(String value) {
            addCriterion("goods_sn like", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnNotLike(String value) {
            addCriterion("goods_sn not like", value, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnIn(List<String> values) {
            addCriterion("goods_sn in", values, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnNotIn(List<String> values) {
            addCriterion("goods_sn not in", values, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnBetween(String value1, String value2) {
            addCriterion("goods_sn between", value1, value2, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andGoodsSnNotBetween(String value1, String value2) {
            addCriterion("goods_sn not between", value1, value2, "goodsSn");
            return (Criteria) this;
        }

        public Criteria andColorCodeIsNull() {
            addCriterion("color_code is null");
            return (Criteria) this;
        }

        public Criteria andColorCodeIsNotNull() {
            addCriterion("color_code is not null");
            return (Criteria) this;
        }

        public Criteria andColorCodeEqualTo(String value) {
            addCriterion("color_code =", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeNotEqualTo(String value) {
            addCriterion("color_code <>", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeGreaterThan(String value) {
            addCriterion("color_code >", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeGreaterThanOrEqualTo(String value) {
            addCriterion("color_code >=", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeLessThan(String value) {
            addCriterion("color_code <", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeLessThanOrEqualTo(String value) {
            addCriterion("color_code <=", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeLike(String value) {
            addCriterion("color_code like", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeNotLike(String value) {
            addCriterion("color_code not like", value, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeIn(List<String> values) {
            addCriterion("color_code in", values, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeNotIn(List<String> values) {
            addCriterion("color_code not in", values, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeBetween(String value1, String value2) {
            addCriterion("color_code between", value1, value2, "colorCode");
            return (Criteria) this;
        }

        public Criteria andColorCodeNotBetween(String value1, String value2) {
            addCriterion("color_code not between", value1, value2, "colorCode");
            return (Criteria) this;
        }

        public Criteria andSizeCodeIsNull() {
            addCriterion("size_code is null");
            return (Criteria) this;
        }

        public Criteria andSizeCodeIsNotNull() {
            addCriterion("size_code is not null");
            return (Criteria) this;
        }

        public Criteria andSizeCodeEqualTo(String value) {
            addCriterion("size_code =", value, "sizeCode");
            return (Criteria) this;
        }

        public Criteria andSizeCodeNotEqualTo(String value) {
            addCriterion("size_code <>", value, "sizeCode");
            return (Criteria) this;
        }

        public Criteria andSizeCodeGreaterThan(String value) {
            addCriterion("size_code >", value, "sizeCode");
            return (Criteria) this;
        }

        public Criteria andSizeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("size_code >=", value, "sizeCode");
            return (Criteria) this;
        }

        public Criteria andSizeCodeLessThan(String value) {
            addCriterion("size_code <", value, "sizeCode");
            return (Criteria) this;
        }

        public Criteria andSizeCodeLessThanOrEqualTo(String value) {
            addCriterion("size_code <=", value, "sizeCode");
            return (Criteria) this;
        }

        public Criteria andSizeCodeLike(String value) {
            addCriterion("size_code like", value, "sizeCode");
            return (Criteria) this;
        }

        public Criteria andSizeCodeNotLike(String value) {
            addCriterion("size_code not like", value, "sizeCode");
            return (Criteria) this;
        }

        public Criteria andSizeCodeIn(List<String> values) {
            addCriterion("size_code in", values, "sizeCode");
            return (Criteria) this;
        }

        public Criteria andSizeCodeNotIn(List<String> values) {
            addCriterion("size_code not in", values, "sizeCode");
            return (Criteria) this;
        }

        public Criteria andSizeCodeBetween(String value1, String value2) {
            addCriterion("size_code between", value1, value2, "sizeCode");
            return (Criteria) this;
        }

        public Criteria andSizeCodeNotBetween(String value1, String value2) {
            addCriterion("size_code not between", value1, value2, "sizeCode");
            return (Criteria) this;
        }

        public Criteria andActualNumberIsNull() {
            addCriterion("actual_number is null");
            return (Criteria) this;
        }

        public Criteria andActualNumberIsNotNull() {
            addCriterion("actual_number is not null");
            return (Criteria) this;
        }

        public Criteria andActualNumberEqualTo(Integer value) {
            addCriterion("actual_number =", value, "actualNumber");
            return (Criteria) this;
        }

        public Criteria andActualNumberNotEqualTo(Integer value) {
            addCriterion("actual_number <>", value, "actualNumber");
            return (Criteria) this;
        }

        public Criteria andActualNumberGreaterThan(Integer value) {
            addCriterion("actual_number >", value, "actualNumber");
            return (Criteria) this;
        }

        public Criteria andActualNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("actual_number >=", value, "actualNumber");
            return (Criteria) this;
        }

        public Criteria andActualNumberLessThan(Integer value) {
            addCriterion("actual_number <", value, "actualNumber");
            return (Criteria) this;
        }

        public Criteria andActualNumberLessThanOrEqualTo(Integer value) {
            addCriterion("actual_number <=", value, "actualNumber");
            return (Criteria) this;
        }

        public Criteria andActualNumberIn(List<Integer> values) {
            addCriterion("actual_number in", values, "actualNumber");
            return (Criteria) this;
        }

        public Criteria andActualNumberNotIn(List<Integer> values) {
            addCriterion("actual_number not in", values, "actualNumber");
            return (Criteria) this;
        }

        public Criteria andActualNumberBetween(Integer value1, Integer value2) {
            addCriterion("actual_number between", value1, value2, "actualNumber");
            return (Criteria) this;
        }

        public Criteria andActualNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("actual_number not between", value1, value2, "actualNumber");
            return (Criteria) this;
        }

        public Criteria andAvailableNumberIsNull() {
            addCriterion("available_number is null");
            return (Criteria) this;
        }

        public Criteria andAvailableNumberIsNotNull() {
            addCriterion("available_number is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableNumberEqualTo(Integer value) {
            addCriterion("available_number =", value, "availableNumber");
            return (Criteria) this;
        }

        public Criteria andAvailableNumberNotEqualTo(Integer value) {
            addCriterion("available_number <>", value, "availableNumber");
            return (Criteria) this;
        }

        public Criteria andAvailableNumberGreaterThan(Integer value) {
            addCriterion("available_number >", value, "availableNumber");
            return (Criteria) this;
        }

        public Criteria andAvailableNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("available_number >=", value, "availableNumber");
            return (Criteria) this;
        }

        public Criteria andAvailableNumberLessThan(Integer value) {
            addCriterion("available_number <", value, "availableNumber");
            return (Criteria) this;
        }

        public Criteria andAvailableNumberLessThanOrEqualTo(Integer value) {
            addCriterion("available_number <=", value, "availableNumber");
            return (Criteria) this;
        }

        public Criteria andAvailableNumberIn(List<Integer> values) {
            addCriterion("available_number in", values, "availableNumber");
            return (Criteria) this;
        }

        public Criteria andAvailableNumberNotIn(List<Integer> values) {
            addCriterion("available_number not in", values, "availableNumber");
            return (Criteria) this;
        }

        public Criteria andAvailableNumberBetween(Integer value1, Integer value2) {
            addCriterion("available_number between", value1, value2, "availableNumber");
            return (Criteria) this;
        }

        public Criteria andAvailableNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("available_number not between", value1, value2, "availableNumber");
            return (Criteria) this;
        }

        public Criteria andStockNumberIsNull() {
            addCriterion("stock_number is null");
            return (Criteria) this;
        }

        public Criteria andStockNumberIsNotNull() {
            addCriterion("stock_number is not null");
            return (Criteria) this;
        }

        public Criteria andStockNumberEqualTo(Integer value) {
            addCriterion("stock_number =", value, "stockNumber");
            return (Criteria) this;
        }

        public Criteria andStockNumberNotEqualTo(Integer value) {
            addCriterion("stock_number <>", value, "stockNumber");
            return (Criteria) this;
        }

        public Criteria andStockNumberGreaterThan(Integer value) {
            addCriterion("stock_number >", value, "stockNumber");
            return (Criteria) this;
        }

        public Criteria andStockNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("stock_number >=", value, "stockNumber");
            return (Criteria) this;
        }

        public Criteria andStockNumberLessThan(Integer value) {
            addCriterion("stock_number <", value, "stockNumber");
            return (Criteria) this;
        }

        public Criteria andStockNumberLessThanOrEqualTo(Integer value) {
            addCriterion("stock_number <=", value, "stockNumber");
            return (Criteria) this;
        }

        public Criteria andStockNumberIn(List<Integer> values) {
            addCriterion("stock_number in", values, "stockNumber");
            return (Criteria) this;
        }

        public Criteria andStockNumberNotIn(List<Integer> values) {
            addCriterion("stock_number not in", values, "stockNumber");
            return (Criteria) this;
        }

        public Criteria andStockNumberBetween(Integer value1, Integer value2) {
            addCriterion("stock_number between", value1, value2, "stockNumber");
            return (Criteria) this;
        }

        public Criteria andStockNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("stock_number not between", value1, value2, "stockNumber");
            return (Criteria) this;
        }

        public Criteria andAlertNumberIsNull() {
            addCriterion("alert_number is null");
            return (Criteria) this;
        }

        public Criteria andAlertNumberIsNotNull() {
            addCriterion("alert_number is not null");
            return (Criteria) this;
        }

        public Criteria andAlertNumberEqualTo(Integer value) {
            addCriterion("alert_number =", value, "alertNumber");
            return (Criteria) this;
        }

        public Criteria andAlertNumberNotEqualTo(Integer value) {
            addCriterion("alert_number <>", value, "alertNumber");
            return (Criteria) this;
        }

        public Criteria andAlertNumberGreaterThan(Integer value) {
            addCriterion("alert_number >", value, "alertNumber");
            return (Criteria) this;
        }

        public Criteria andAlertNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("alert_number >=", value, "alertNumber");
            return (Criteria) this;
        }

        public Criteria andAlertNumberLessThan(Integer value) {
            addCriterion("alert_number <", value, "alertNumber");
            return (Criteria) this;
        }

        public Criteria andAlertNumberLessThanOrEqualTo(Integer value) {
            addCriterion("alert_number <=", value, "alertNumber");
            return (Criteria) this;
        }

        public Criteria andAlertNumberIn(List<Integer> values) {
            addCriterion("alert_number in", values, "alertNumber");
            return (Criteria) this;
        }

        public Criteria andAlertNumberNotIn(List<Integer> values) {
            addCriterion("alert_number not in", values, "alertNumber");
            return (Criteria) this;
        }

        public Criteria andAlertNumberBetween(Integer value1, Integer value2) {
            addCriterion("alert_number between", value1, value2, "alertNumber");
            return (Criteria) this;
        }

        public Criteria andAlertNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("alert_number not between", value1, value2, "alertNumber");
            return (Criteria) this;
        }

        public Criteria andPresaleNumberIsNull() {
            addCriterion("presale_number is null");
            return (Criteria) this;
        }

        public Criteria andPresaleNumberIsNotNull() {
            addCriterion("presale_number is not null");
            return (Criteria) this;
        }

        public Criteria andPresaleNumberEqualTo(Integer value) {
            addCriterion("presale_number =", value, "presaleNumber");
            return (Criteria) this;
        }

        public Criteria andPresaleNumberNotEqualTo(Integer value) {
            addCriterion("presale_number <>", value, "presaleNumber");
            return (Criteria) this;
        }

        public Criteria andPresaleNumberGreaterThan(Integer value) {
            addCriterion("presale_number >", value, "presaleNumber");
            return (Criteria) this;
        }

        public Criteria andPresaleNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("presale_number >=", value, "presaleNumber");
            return (Criteria) this;
        }

        public Criteria andPresaleNumberLessThan(Integer value) {
            addCriterion("presale_number <", value, "presaleNumber");
            return (Criteria) this;
        }

        public Criteria andPresaleNumberLessThanOrEqualTo(Integer value) {
            addCriterion("presale_number <=", value, "presaleNumber");
            return (Criteria) this;
        }

        public Criteria andPresaleNumberIn(List<Integer> values) {
            addCriterion("presale_number in", values, "presaleNumber");
            return (Criteria) this;
        }

        public Criteria andPresaleNumberNotIn(List<Integer> values) {
            addCriterion("presale_number not in", values, "presaleNumber");
            return (Criteria) this;
        }

        public Criteria andPresaleNumberBetween(Integer value1, Integer value2) {
            addCriterion("presale_number between", value1, value2, "presaleNumber");
            return (Criteria) this;
        }

        public Criteria andPresaleNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("presale_number not between", value1, value2, "presaleNumber");
            return (Criteria) this;
        }

        public Criteria andOnsellNumIsNull() {
            addCriterion("onsell_num is null");
            return (Criteria) this;
        }

        public Criteria andOnsellNumIsNotNull() {
            addCriterion("onsell_num is not null");
            return (Criteria) this;
        }

        public Criteria andOnsellNumEqualTo(Integer value) {
            addCriterion("onsell_num =", value, "onsellNum");
            return (Criteria) this;
        }

        public Criteria andOnsellNumNotEqualTo(Integer value) {
            addCriterion("onsell_num <>", value, "onsellNum");
            return (Criteria) this;
        }

        public Criteria andOnsellNumGreaterThan(Integer value) {
            addCriterion("onsell_num >", value, "onsellNum");
            return (Criteria) this;
        }

        public Criteria andOnsellNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("onsell_num >=", value, "onsellNum");
            return (Criteria) this;
        }

        public Criteria andOnsellNumLessThan(Integer value) {
            addCriterion("onsell_num <", value, "onsellNum");
            return (Criteria) this;
        }

        public Criteria andOnsellNumLessThanOrEqualTo(Integer value) {
            addCriterion("onsell_num <=", value, "onsellNum");
            return (Criteria) this;
        }

        public Criteria andOnsellNumIn(List<Integer> values) {
            addCriterion("onsell_num in", values, "onsellNum");
            return (Criteria) this;
        }

        public Criteria andOnsellNumNotIn(List<Integer> values) {
            addCriterion("onsell_num not in", values, "onsellNum");
            return (Criteria) this;
        }

        public Criteria andOnsellNumBetween(Integer value1, Integer value2) {
            addCriterion("onsell_num between", value1, value2, "onsellNum");
            return (Criteria) this;
        }

        public Criteria andOnsellNumNotBetween(Integer value1, Integer value2) {
            addCriterion("onsell_num not between", value1, value2, "onsellNum");
            return (Criteria) this;
        }

        public Criteria andMaxOnsellNumIsNull() {
            addCriterion("max_onsell_num is null");
            return (Criteria) this;
        }

        public Criteria andMaxOnsellNumIsNotNull() {
            addCriterion("max_onsell_num is not null");
            return (Criteria) this;
        }

        public Criteria andMaxOnsellNumEqualTo(Integer value) {
            addCriterion("max_onsell_num =", value, "maxOnsellNum");
            return (Criteria) this;
        }

        public Criteria andMaxOnsellNumNotEqualTo(Integer value) {
            addCriterion("max_onsell_num <>", value, "maxOnsellNum");
            return (Criteria) this;
        }

        public Criteria andMaxOnsellNumGreaterThan(Integer value) {
            addCriterion("max_onsell_num >", value, "maxOnsellNum");
            return (Criteria) this;
        }

        public Criteria andMaxOnsellNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_onsell_num >=", value, "maxOnsellNum");
            return (Criteria) this;
        }

        public Criteria andMaxOnsellNumLessThan(Integer value) {
            addCriterion("max_onsell_num <", value, "maxOnsellNum");
            return (Criteria) this;
        }

        public Criteria andMaxOnsellNumLessThanOrEqualTo(Integer value) {
            addCriterion("max_onsell_num <=", value, "maxOnsellNum");
            return (Criteria) this;
        }

        public Criteria andMaxOnsellNumIn(List<Integer> values) {
            addCriterion("max_onsell_num in", values, "maxOnsellNum");
            return (Criteria) this;
        }

        public Criteria andMaxOnsellNumNotIn(List<Integer> values) {
            addCriterion("max_onsell_num not in", values, "maxOnsellNum");
            return (Criteria) this;
        }

        public Criteria andMaxOnsellNumBetween(Integer value1, Integer value2) {
            addCriterion("max_onsell_num between", value1, value2, "maxOnsellNum");
            return (Criteria) this;
        }

        public Criteria andMaxOnsellNumNotBetween(Integer value1, Integer value2) {
            addCriterion("max_onsell_num not between", value1, value2, "maxOnsellNum");
            return (Criteria) this;
        }

        public Criteria andSpecPriceIsNull() {
            addCriterion("spec_price is null");
            return (Criteria) this;
        }

        public Criteria andSpecPriceIsNotNull() {
            addCriterion("spec_price is not null");
            return (Criteria) this;
        }

        public Criteria andSpecPriceEqualTo(String value) {
            addCriterion("spec_price =", value, "specPrice");
            return (Criteria) this;
        }

        public Criteria andSpecPriceNotEqualTo(String value) {
            addCriterion("spec_price <>", value, "specPrice");
            return (Criteria) this;
        }

        public Criteria andSpecPriceGreaterThan(String value) {
            addCriterion("spec_price >", value, "specPrice");
            return (Criteria) this;
        }

        public Criteria andSpecPriceGreaterThanOrEqualTo(String value) {
            addCriterion("spec_price >=", value, "specPrice");
            return (Criteria) this;
        }

        public Criteria andSpecPriceLessThan(String value) {
            addCriterion("spec_price <", value, "specPrice");
            return (Criteria) this;
        }

        public Criteria andSpecPriceLessThanOrEqualTo(String value) {
            addCriterion("spec_price <=", value, "specPrice");
            return (Criteria) this;
        }

        public Criteria andSpecPriceLike(String value) {
            addCriterion("spec_price like", value, "specPrice");
            return (Criteria) this;
        }

        public Criteria andSpecPriceNotLike(String value) {
            addCriterion("spec_price not like", value, "specPrice");
            return (Criteria) this;
        }

        public Criteria andSpecPriceIn(List<String> values) {
            addCriterion("spec_price in", values, "specPrice");
            return (Criteria) this;
        }

        public Criteria andSpecPriceNotIn(List<String> values) {
            addCriterion("spec_price not in", values, "specPrice");
            return (Criteria) this;
        }

        public Criteria andSpecPriceBetween(String value1, String value2) {
            addCriterion("spec_price between", value1, value2, "specPrice");
            return (Criteria) this;
        }

        public Criteria andSpecPriceNotBetween(String value1, String value2) {
            addCriterion("spec_price not between", value1, value2, "specPrice");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean limitValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isLimitValue() {
            return limitValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            if("limit".equals(condition))
              this.limitValue = true;
            else
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}