package com.work.shop.bean;

import java.util.Date;

public class ChannelApiLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_api_log.log_id
     *
     * @mbggenerated
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_api_log.channel_code
     *
     * @mbggenerated
     */
    private String channelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_api_log.shop_code
     *
     * @mbggenerated
     */
    private String shopCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_api_log.method_name
     *
     * @mbggenerated
     */
    private String methodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_api_log.param_info
     *
     * @mbggenerated
     */
    private String paramInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_api_log.return_code
     *
     * @mbggenerated
     */
    private String returnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_api_log.return_Message
     *
     * @mbggenerated
     */
    private String returnMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_api_log.ip_address
     *
     * @mbggenerated
     */
    private String ipAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_api_log.user
     *
     * @mbggenerated
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_api_log.request_time
     *
     * @mbggenerated
     */
    private Date requestTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_api_log.log_id
     *
     * @return the value of channel_api_log.log_id
     *
     * @mbggenerated
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_api_log.log_id
     *
     * @param logId the value for channel_api_log.log_id
     *
     * @mbggenerated
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_api_log.channel_code
     *
     * @return the value of channel_api_log.channel_code
     *
     * @mbggenerated
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_api_log.channel_code
     *
     * @param channelCode the value for channel_api_log.channel_code
     *
     * @mbggenerated
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_api_log.shop_code
     *
     * @return the value of channel_api_log.shop_code
     *
     * @mbggenerated
     */
    public String getShopCode() {
        return shopCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_api_log.shop_code
     *
     * @param shopCode the value for channel_api_log.shop_code
     *
     * @mbggenerated
     */
    public void setShopCode(String shopCode) {
        this.shopCode = shopCode == null ? null : shopCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_api_log.method_name
     *
     * @return the value of channel_api_log.method_name
     *
     * @mbggenerated
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_api_log.method_name
     *
     * @param methodName the value for channel_api_log.method_name
     *
     * @mbggenerated
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_api_log.param_info
     *
     * @return the value of channel_api_log.param_info
     *
     * @mbggenerated
     */
    public String getParamInfo() {
        return paramInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_api_log.param_info
     *
     * @param paramInfo the value for channel_api_log.param_info
     *
     * @mbggenerated
     */
    public void setParamInfo(String paramInfo) {
        this.paramInfo = paramInfo == null ? null : paramInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_api_log.return_code
     *
     * @return the value of channel_api_log.return_code
     *
     * @mbggenerated
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_api_log.return_code
     *
     * @param returnCode the value for channel_api_log.return_code
     *
     * @mbggenerated
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode == null ? null : returnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_api_log.return_Message
     *
     * @return the value of channel_api_log.return_Message
     *
     * @mbggenerated
     */
    public String getReturnMessage() {
        return returnMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_api_log.return_Message
     *
     * @param returnMessage the value for channel_api_log.return_Message
     *
     * @mbggenerated
     */
    public void setReturnMessage(String returnMessage) {
        this.returnMessage = returnMessage == null ? null : returnMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_api_log.ip_address
     *
     * @return the value of channel_api_log.ip_address
     *
     * @mbggenerated
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_api_log.ip_address
     *
     * @param ipAddress the value for channel_api_log.ip_address
     *
     * @mbggenerated
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress == null ? null : ipAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_api_log.user
     *
     * @return the value of channel_api_log.user
     *
     * @mbggenerated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_api_log.user
     *
     * @param user the value for channel_api_log.user
     *
     * @mbggenerated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_api_log.request_time
     *
     * @return the value of channel_api_log.request_time
     *
     * @mbggenerated
     */
    public Date getRequestTime() {
        return requestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_api_log.request_time
     *
     * @param requestTime the value for channel_api_log.request_time
     *
     * @mbggenerated
     */
    public void setRequestTime(Date requestTime) {
        this.requestTime = requestTime;
    }
}