package com.work.shop.bean;

import java.math.BigDecimal;
import java.util.Date;

public class GroupGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_goods.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_goods.group_code
     *
     * @mbggenerated
     */
    private String groupCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_goods.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_goods.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_goods.Id
     *
     * @return the value of group_goods.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_goods.Id
     *
     * @param id the value for group_goods.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_goods.group_code
     *
     * @return the value of group_goods.group_code
     *
     * @mbggenerated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_goods.group_code
     *
     * @param groupCode the value for group_goods.group_code
     *
     * @mbggenerated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode == null ? null : groupCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_goods.price
     *
     * @return the value of group_goods.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_goods.price
     *
     * @param price the value for group_goods.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_goods.add_time
     *
     * @return the value of group_goods.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_goods.add_time
     *
     * @param addTime the value for group_goods.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }
}