package com.work.shop.bean;

import java.math.BigDecimal;

public class LuckyBagGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_bag_goods.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_bag_goods.warehouse_id
     *
     * @mbggenerated
     */
    private String warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_bag_goods.sku
     *
     * @mbggenerated
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_bag_goods.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_bag_goods.goods_price
     *
     * @mbggenerated
     */
    private BigDecimal goodsPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_bag_goods.pre_stock_number
     *
     * @mbggenerated
     */
    private Integer preStockNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_bag_goods.act_stock_number
     *
     * @mbggenerated
     */
    private Integer actStockNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_bag_goods.id
     *
     * @return the value of lucky_bag_goods.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_bag_goods.id
     *
     * @param id the value for lucky_bag_goods.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_bag_goods.warehouse_id
     *
     * @return the value of lucky_bag_goods.warehouse_id
     *
     * @mbggenerated
     */
    public String getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_bag_goods.warehouse_id
     *
     * @param warehouseId the value for lucky_bag_goods.warehouse_id
     *
     * @mbggenerated
     */
    public void setWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId == null ? null : warehouseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_bag_goods.sku
     *
     * @return the value of lucky_bag_goods.sku
     *
     * @mbggenerated
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_bag_goods.sku
     *
     * @param sku the value for lucky_bag_goods.sku
     *
     * @mbggenerated
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_bag_goods.goods_name
     *
     * @return the value of lucky_bag_goods.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_bag_goods.goods_name
     *
     * @param goodsName the value for lucky_bag_goods.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_bag_goods.goods_price
     *
     * @return the value of lucky_bag_goods.goods_price
     *
     * @mbggenerated
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_bag_goods.goods_price
     *
     * @param goodsPrice the value for lucky_bag_goods.goods_price
     *
     * @mbggenerated
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_bag_goods.pre_stock_number
     *
     * @return the value of lucky_bag_goods.pre_stock_number
     *
     * @mbggenerated
     */
    public Integer getPreStockNumber() {
        return preStockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_bag_goods.pre_stock_number
     *
     * @param preStockNumber the value for lucky_bag_goods.pre_stock_number
     *
     * @mbggenerated
     */
    public void setPreStockNumber(Integer preStockNumber) {
        this.preStockNumber = preStockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_bag_goods.act_stock_number
     *
     * @return the value of lucky_bag_goods.act_stock_number
     *
     * @mbggenerated
     */
    public Integer getActStockNumber() {
        return actStockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_bag_goods.act_stock_number
     *
     * @param actStockNumber the value for lucky_bag_goods.act_stock_number
     *
     * @mbggenerated
     */
    public void setActStockNumber(Integer actStockNumber) {
        this.actStockNumber = actStockNumber;
    }
}