package com.work.shop.bean;

import java.math.BigDecimal;
import java.util.Date;

public class LuckyBag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_bag.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_bag.warehouse_id
     *
     * @mbggenerated
     */
    private String warehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_bag.lucky_bag_sku
     *
     * @mbggenerated
     */
    private String luckyBagSku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_bag.lucky_bag_price
     *
     * @mbggenerated
     */
    private BigDecimal luckyBagPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_bag.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lucky_bag.is_valuable
     *
     * @mbggenerated
     */
    private String isValuable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_bag.id
     *
     * @return the value of lucky_bag.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_bag.id
     *
     * @param id the value for lucky_bag.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_bag.warehouse_id
     *
     * @return the value of lucky_bag.warehouse_id
     *
     * @mbggenerated
     */
    public String getWarehouseId() {
        return warehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_bag.warehouse_id
     *
     * @param warehouseId the value for lucky_bag.warehouse_id
     *
     * @mbggenerated
     */
    public void setWarehouseId(String warehouseId) {
        this.warehouseId = warehouseId == null ? null : warehouseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_bag.lucky_bag_sku
     *
     * @return the value of lucky_bag.lucky_bag_sku
     *
     * @mbggenerated
     */
    public String getLuckyBagSku() {
        return luckyBagSku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_bag.lucky_bag_sku
     *
     * @param luckyBagSku the value for lucky_bag.lucky_bag_sku
     *
     * @mbggenerated
     */
    public void setLuckyBagSku(String luckyBagSku) {
        this.luckyBagSku = luckyBagSku == null ? null : luckyBagSku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_bag.lucky_bag_price
     *
     * @return the value of lucky_bag.lucky_bag_price
     *
     * @mbggenerated
     */
    public BigDecimal getLuckyBagPrice() {
        return luckyBagPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_bag.lucky_bag_price
     *
     * @param luckyBagPrice the value for lucky_bag.lucky_bag_price
     *
     * @mbggenerated
     */
    public void setLuckyBagPrice(BigDecimal luckyBagPrice) {
        this.luckyBagPrice = luckyBagPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_bag.add_time
     *
     * @return the value of lucky_bag.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_bag.add_time
     *
     * @param addTime the value for lucky_bag.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lucky_bag.is_valuable
     *
     * @return the value of lucky_bag.is_valuable
     *
     * @mbggenerated
     */
    public String getIsValuable() {
        return isValuable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lucky_bag.is_valuable
     *
     * @param isValuable the value for lucky_bag.is_valuable
     *
     * @mbggenerated
     */
    public void setIsValuable(String isValuable) {
        this.isValuable = isValuable == null ? null : isValuable.trim();
    }
}