package com.work.shop.dao.bgcontentdb;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.bgcontentdb.BGchannelGoods;
import com.work.shop.bean.bgcontentdb.BGchannelGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BGchannelGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(BGchannelGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(BGchannelGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int insert(BGchannelGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(BGchannelGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    List<BGchannelGoods> selectByExample(BGchannelGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods
     *
     * @mbggenerated
     */
    BGchannelGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") BGchannelGoods record, @Param("example") BGchannelGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") BGchannelGoods record, @Param("example") BGchannelGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(BGchannelGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(BGchannelGoods record);
}