package com.work.shop.dao.bgcontentdb;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.bgcontentdb.BGchannelGoodsExtension;
import com.work.shop.bean.bgcontentdb.BGchannelGoodsExtensionExample;
import com.work.shop.bean.bgcontentdb.BGchannelGoodsExtensionWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BGchannelGoodsExtensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_extension
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(BGchannelGoodsExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_extension
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(BGchannelGoodsExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_extension
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_extension
     *
     * @mbggenerated
     */
    @Writer
    int insert(BGchannelGoodsExtensionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_extension
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(BGchannelGoodsExtensionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_extension
     *
     * @mbggenerated
     */
    @ReadOnly
    List<BGchannelGoodsExtensionWithBLOBs> selectByExampleWithBLOBs(BGchannelGoodsExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_extension
     *
     * @mbggenerated
     */
    @ReadOnly
    List<BGchannelGoodsExtension> selectByExample(BGchannelGoodsExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_extension
     *
     * @mbggenerated
     */
    BGchannelGoodsExtensionWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_extension
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") BGchannelGoodsExtensionWithBLOBs record, @Param("example") BGchannelGoodsExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_extension
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") BGchannelGoodsExtensionWithBLOBs record, @Param("example") BGchannelGoodsExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_extension
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") BGchannelGoodsExtension record, @Param("example") BGchannelGoodsExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_extension
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(BGchannelGoodsExtensionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_extension
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(BGchannelGoodsExtensionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_extension
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(BGchannelGoodsExtension record);
}