package com.work.shop.dao.bgcontentdb;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.shop.bean.bgcontentdb.BGproductBarcodeList;
import com.work.shop.bean.bgcontentdb.BGproductBarcodeListExample;
import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;

public interface BGproductBarcodeListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_barcode_list
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(BGproductBarcodeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_barcode_list
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(BGproductBarcodeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_barcode_list
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_barcode_list
     *
     * @mbggenerated
     */
    @Writer
    int insert(BGproductBarcodeList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_barcode_list
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(BGproductBarcodeList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_barcode_list
     *
     * @mbggenerated
     */
    @ReadOnly
    List<BGproductBarcodeList> selectByExample(BGproductBarcodeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_barcode_list
     *
     * @mbggenerated
     */
    BGproductBarcodeList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_barcode_list
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") BGproductBarcodeList record, @Param("example") BGproductBarcodeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_barcode_list
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") BGproductBarcodeList record, @Param("example") BGproductBarcodeListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_barcode_list
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(BGproductBarcodeList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_barcode_list
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(BGproductBarcodeList record);
}