package com.work.shop.dao.bgcontentdb;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.bgcontentdb.BGproductGoods;
import com.work.shop.bean.bgcontentdb.BGproductGoodsExample;
import com.work.shop.bean.bgcontentdb.BGproductGoodsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BGproductGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(BGproductGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(BGproductGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(String goodsSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_goods
     *
     * @mbggenerated
     */
    @Writer
    int insert(BGproductGoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_goods
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(BGproductGoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    List<BGproductGoodsWithBLOBs> selectByExampleWithBLOBs(BGproductGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    List<BGproductGoods> selectByExample(BGproductGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_goods
     *
     * @mbggenerated
     */
    BGproductGoodsWithBLOBs selectByPrimaryKey(String goodsSn);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") BGproductGoodsWithBLOBs record, @Param("example") BGproductGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") BGproductGoodsWithBLOBs record, @Param("example") BGproductGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") BGproductGoods record, @Param("example") BGproductGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(BGproductGoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(BGproductGoodsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(BGproductGoods record);
}