package com.work.shop.dao.bgcontentdb;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.bgcontentdb.BGproductAttrValues;
import com.work.shop.bean.bgcontentdb.BGproductAttrValuesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BGproductAttrValuesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(BGproductAttrValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(BGproductAttrValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int insert(BGproductAttrValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(BGproductAttrValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @ReadOnly
    List<BGproductAttrValues> selectByExample(BGproductAttrValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    BGproductAttrValues selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") BGproductAttrValues record, @Param("example") BGproductAttrValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") BGproductAttrValues record, @Param("example") BGproductAttrValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(BGproductAttrValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(BGproductAttrValues record);
}