package com.work.shop.dao.mbproduct;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.mbproduct.MBProductLibBrand;
import com.work.shop.bean.mbproduct.MBProductLibBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBProductLibBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(MBProductLibBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(MBProductLibBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int insert(MBProductLibBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(MBProductLibBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @ReadOnly
    List<MBProductLibBrand> selectByExampleWithBLOBs(MBProductLibBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @ReadOnly
    List<MBProductLibBrand> selectByExample(MBProductLibBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    MBProductLibBrand selectByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") MBProductLibBrand record, @Param("example") MBProductLibBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") MBProductLibBrand record, @Param("example") MBProductLibBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") MBProductLibBrand record, @Param("example") MBProductLibBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(MBProductLibBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(MBProductLibBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(MBProductLibBrand record);
}