package com.work.shop.dao.mbproduct;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.mbproduct.MBProductLibCategory;
import com.work.shop.bean.mbproduct.MBProductLibCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBProductLibCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_category
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(MBProductLibCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_category
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(MBProductLibCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_category
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_category
     *
     * @mbggenerated
     */
    @Writer
    int insert(MBProductLibCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_category
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(MBProductLibCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_category
     *
     * @mbggenerated
     */
    @ReadOnly
    List<MBProductLibCategory> selectByExample(MBProductLibCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_category
     *
     * @mbggenerated
     */
    MBProductLibCategory selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_category
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") MBProductLibCategory record, @Param("example") MBProductLibCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_category
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") MBProductLibCategory record, @Param("example") MBProductLibCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_category
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(MBProductLibCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_category
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(MBProductLibCategory record);
}