package com.work.shop.dao.mbproduct;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.mbproduct.MBProductSellerGoodsBarcode;
import com.work.shop.bean.mbproduct.MBProductSellerGoodsBarcodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBProductSellerGoodsBarcodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(MBProductSellerGoodsBarcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(MBProductSellerGoodsBarcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Long barcodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int insert(MBProductSellerGoodsBarcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(MBProductSellerGoodsBarcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @ReadOnly
    List<MBProductSellerGoodsBarcode> selectByExample(MBProductSellerGoodsBarcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    MBProductSellerGoodsBarcode selectByPrimaryKey(Long barcodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") MBProductSellerGoodsBarcode record, @Param("example") MBProductSellerGoodsBarcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") MBProductSellerGoodsBarcode record, @Param("example") MBProductSellerGoodsBarcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(MBProductSellerGoodsBarcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(MBProductSellerGoodsBarcode record);
}