package com.work.shop.dao.mbproduct;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.mbproduct.MBProductSellerGoodsGallery;
import com.work.shop.bean.mbproduct.MBProductSellerGoodsGalleryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MBProductSellerGoodsGalleryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_gallery
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(MBProductSellerGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_gallery
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(MBProductSellerGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_gallery
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_gallery
     *
     * @mbggenerated
     */
    @Writer
    int insert(MBProductSellerGoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_gallery
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(MBProductSellerGoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_gallery
     *
     * @mbggenerated
     */
    @ReadOnly
    List<MBProductSellerGoodsGallery> selectByExample(MBProductSellerGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_gallery
     *
     * @mbggenerated
     */
    MBProductSellerGoodsGallery selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_gallery
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") MBProductSellerGoodsGallery record, @Param("example") MBProductSellerGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_gallery
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") MBProductSellerGoodsGallery record, @Param("example") MBProductSellerGoodsGalleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_gallery
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(MBProductSellerGoodsGallery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_gallery
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(MBProductSellerGoodsGallery record);
}