package com.work.shop.dao.mbproduct;

import com.work.shop.bean.mbproduct.ProductChannelGoodsDetail;
import com.work.shop.bean.mbproduct.ProductChannelGoodsDetailExample;
import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductChannelGoodsDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods_detail
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ProductChannelGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods_detail
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ProductChannelGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods_detail
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods_detail
     *
     * @mbggenerated
     */
    @Writer
    int insert(ProductChannelGoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods_detail
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ProductChannelGoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods_detail
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ProductChannelGoodsDetail> selectByExampleWithBLOBs(ProductChannelGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods_detail
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ProductChannelGoodsDetail> selectByExample(ProductChannelGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods_detail
     *
     * @mbggenerated
     */
    ProductChannelGoodsDetail selectByPrimaryKey(Integer detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods_detail
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ProductChannelGoodsDetail record, @Param("example") ProductChannelGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods_detail
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") ProductChannelGoodsDetail record, @Param("example") ProductChannelGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods_detail
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ProductChannelGoodsDetail record, @Param("example") ProductChannelGoodsDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods_detail
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ProductChannelGoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods_detail
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(ProductChannelGoodsDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods_detail
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ProductChannelGoodsDetail record);
}