package com.work.shop.dao.mbproduct;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.mbproduct.ProductLibAttrValue;
import com.work.shop.bean.mbproduct.ProductLibAttrValueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductLibAttrValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_attr_value
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ProductLibAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_attr_value
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ProductLibAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_attr_value
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer attrValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_attr_value
     *
     * @mbggenerated
     */
    @Writer
    int insert(ProductLibAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_attr_value
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ProductLibAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_attr_value
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ProductLibAttrValue> selectByExample(ProductLibAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_attr_value
     *
     * @mbggenerated
     */
    ProductLibAttrValue selectByPrimaryKey(Integer attrValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_attr_value
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ProductLibAttrValue record, @Param("example") ProductLibAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_attr_value
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ProductLibAttrValue record, @Param("example") ProductLibAttrValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_attr_value
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ProductLibAttrValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_attr_value
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ProductLibAttrValue record);
}