package com.work.shop.dao.mbproduct;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.work.shop.bean.mbproduct.ProductSellerGoodsBarcode;
import com.work.shop.bean.mbproduct.ProductSellerGoodsBarcodeExample;
import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;

public interface ProductSellerGoodsBarcodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ProductSellerGoodsBarcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ProductSellerGoodsBarcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Long barcodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int insert(ProductSellerGoodsBarcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ProductSellerGoodsBarcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ProductSellerGoodsBarcode> selectByExample(ProductSellerGoodsBarcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    ProductSellerGoodsBarcode selectByPrimaryKey(Long barcodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ProductSellerGoodsBarcode record, @Param("example") ProductSellerGoodsBarcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ProductSellerGoodsBarcode record, @Param("example") ProductSellerGoodsBarcodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ProductSellerGoodsBarcode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods_barcode
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ProductSellerGoodsBarcode record);
}