package com.work.shop.dao.mbproduct;

import com.work.shop.bean.mbproduct.ProductChannelGoods;
import com.work.shop.bean.mbproduct.ProductChannelGoodsExample;
import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductChannelGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ProductChannelGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ProductChannelGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int insert(ProductChannelGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ProductChannelGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ProductChannelGoods> selectByExample(ProductChannelGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods
     *
     * @mbggenerated
     */
    ProductChannelGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ProductChannelGoods record, @Param("example") ProductChannelGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ProductChannelGoods record, @Param("example") ProductChannelGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ProductChannelGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channel_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ProductChannelGoods record);
}