package com.work.shop.dao.mbproduct;

import com.work.shop.bean.mbproduct.ProductSellerGoods;
import com.work.shop.bean.mbproduct.ProductSellerGoodsExample;
import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductSellerGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ProductSellerGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ProductSellerGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods
     *
     * @mbggenerated
     */
    @Writer
    int insert(ProductSellerGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ProductSellerGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ProductSellerGoods> selectByExampleWithBLOBs(ProductSellerGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ProductSellerGoods> selectByExample(ProductSellerGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods
     *
     * @mbggenerated
     */
    ProductSellerGoods selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ProductSellerGoods record, @Param("example") ProductSellerGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") ProductSellerGoods record, @Param("example") ProductSellerGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ProductSellerGoods record, @Param("example") ProductSellerGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ProductSellerGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(ProductSellerGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_seller_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ProductSellerGoods record);
}