package com.work.shop.dao.mbproduct;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.mbproduct.SapProduct;
import com.work.shop.bean.mbproduct.SapProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SapProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_product
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(SapProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_product
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(SapProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_product
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Long barcodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_product
     *
     * @mbggenerated
     */
    @Writer
    int insert(SapProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_product
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(SapProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_product
     *
     * @mbggenerated
     */
    @ReadOnly
    List<SapProduct> selectByExample(SapProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_product
     *
     * @mbggenerated
     */
    SapProduct selectByPrimaryKey(Long barcodeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_product
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") SapProduct record, @Param("example") SapProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_product
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") SapProduct record, @Param("example") SapProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_product
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(SapProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_product
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(SapProduct record);
}