package com.work.shop.dao.mbproduct;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.mbproduct.SapProdCls;
import com.work.shop.bean.mbproduct.SapProdClsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SapProdClsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(SapProdClsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(SapProdClsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    @Writer
    int insert(SapProdCls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(SapProdCls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    @ReadOnly
    List<SapProdCls> selectByExample(SapProdClsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    SapProdCls selectByPrimaryKey(Integer productId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") SapProdCls record, @Param("example") SapProdClsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") SapProdCls record, @Param("example") SapProdClsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(SapProdCls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sap_prod_cls
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(SapProdCls record);
}