package com.work.shop.vo;

public class SystemAreaVO {

    private Integer id;

    private String areaId;

    private String areaType;

    private String areaName;

    private Integer systemArea;

    private String zip;

    private String pid;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAreaId() {
        return areaId;
    }

    public void setAreaId(String areaId) {
        this.areaId = areaId == null ? null : areaId.trim();
    }

    public String getAreaType() {
        return areaType;
    }

    public void setAreaType(String areaType) {
        this.areaType = areaType == null ? null : areaType.trim();
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    public Integer getSystemArea() {
        return systemArea;
    }

    public void setSystemArea(Integer systemArea) {
        this.systemArea = systemArea;
    }

    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_area.zip
     *
     * @param zip the value for system_area.zip
     *
     * @mbggenerated
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column system_area.pid
     *
     * @return the value of system_area.pid
     *
     * @mbggenerated
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column system_area.pid
     *
     * @param pid the value for system_area.pid
     *
     * @mbggenerated
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

	@Override
	public String toString() {
		return "SystemAreaVO [areaId=" + areaId + ", areaType=" + areaType
				+ ", areaName=" + areaName + ", pid=" + pid + "]";
	}
}