package com.work.shop.dao;

import java.util.List;
import java.util.Map;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.bean.ColorAndSize;
import com.work.shop.bean.GoodsProperty;
import com.work.shop.bean.ProductGoodsGalleryVo;
import com.work.shop.bean.ProductGoodsVo;

public interface BgGoodsPropertyMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @ReadOnly
    GoodsProperty selectGoodsProperties(Map<String, Object> map);
    
    @ReadOnly
    List<ColorAndSize> selectDistinctColorAndSize(Map<String, Object> map);

    @ReadOnly
    List<ProductGoodsVo> selectProductGoods(Map<String, Object> map);
    
	@ReadOnly
	List<ProductGoodsGalleryVo> productGoodsGalleryList(Map<String, Object> map);
	
	
}