package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.ChannelStockLog;
import com.work.shop.bean.ChannelStockLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelStockLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock_log
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ChannelStockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock_log
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ChannelStockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock_log
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock_log
     *
     * @mbggenerated
     */
    @Writer
    int insert(ChannelStockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock_log
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ChannelStockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock_log
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ChannelStockLog> selectByExample(ChannelStockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock_log
     *
     * @mbggenerated
     */
    ChannelStockLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ChannelStockLog record, @Param("example") ChannelStockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ChannelStockLog record, @Param("example") ChannelStockLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ChannelStockLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_stock_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ChannelStockLog record);
}