package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.ChannelTemplateModule;
import com.work.shop.bean.ChannelTemplateModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelTemplateModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_module
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ChannelTemplateModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_module
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ChannelTemplateModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_module
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_module
     *
     * @mbggenerated
     */
    @Writer
    int insert(ChannelTemplateModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_module
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ChannelTemplateModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_module
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ChannelTemplateModule> selectByExampleWithBLOBs(ChannelTemplateModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_module
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ChannelTemplateModule> selectByExample(ChannelTemplateModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_module
     *
     * @mbggenerated
     */
    ChannelTemplateModule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_module
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ChannelTemplateModule record, @Param("example") ChannelTemplateModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_module
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") ChannelTemplateModule record, @Param("example") ChannelTemplateModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_module
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ChannelTemplateModule record, @Param("example") ChannelTemplateModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_module
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ChannelTemplateModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_module
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(ChannelTemplateModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template_module
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ChannelTemplateModule record);
}