package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.ChannelApiLog;
import com.work.shop.bean.ChannelApiLogExample;
import com.work.shop.vo.ChannelApiLogVO;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ChannelApiLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_log
     *
     * @mbggenerated
     */
	@Writer
    int countByExample(ChannelApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_log
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ChannelApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_log
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_log
     *
     * @mbggenerated
     */
    @Writer
    int insert(ChannelApiLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_log
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ChannelApiLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_log
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ChannelApiLog> selectByExample(ChannelApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_log
     *
     * @mbggenerated
     */
    ChannelApiLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ChannelApiLog record, @Param("example") ChannelApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ChannelApiLog record, @Param("example") ChannelApiLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ChannelApiLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ChannelApiLog record);
    
    @ReadOnly
    List<ChannelApiLogVO> selectVOByExample(Map<String, Object> params);
}