package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.ChannelErpUpdownLog;
import com.work.shop.bean.ChannelErpUpdownLogExample;
import com.work.shop.vo.ChannelErpUpdownLogVO;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ChannelErpUpdownLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_erp_updown_log
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ChannelErpUpdownLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_erp_updown_log
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ChannelErpUpdownLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_erp_updown_log
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_erp_updown_log
     *
     * @mbggenerated
     */
    @Writer
    int insert(ChannelErpUpdownLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_erp_updown_log
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ChannelErpUpdownLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_erp_updown_log
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ChannelErpUpdownLog> selectByExample(ChannelErpUpdownLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_erp_updown_log
     *
     * @mbggenerated
     */
    ChannelErpUpdownLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_erp_updown_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ChannelErpUpdownLog record, @Param("example") ChannelErpUpdownLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_erp_updown_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ChannelErpUpdownLog record, @Param("example") ChannelErpUpdownLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_erp_updown_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ChannelErpUpdownLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_erp_updown_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ChannelErpUpdownLog record);
    
    @ReadOnly
    List<ChannelErpUpdownLogVO> selectVOByExample(Map<String, Object> params);
}