package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.ChannelTemplate;
import com.work.shop.bean.ChannelTemplateExample;
import com.work.shop.bean.ChannelTemplateWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ChannelTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ChannelTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbggenerated
     */
    @Writer
    int insert(ChannelTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ChannelTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ChannelTemplateWithBLOBs> selectByExampleWithBLOBs(ChannelTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ChannelTemplate> selectByExample(ChannelTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbggenerated
     */
    ChannelTemplateWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ChannelTemplateWithBLOBs record, @Param("example") ChannelTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") ChannelTemplateWithBLOBs record, @Param("example") ChannelTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ChannelTemplate record, @Param("example") ChannelTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ChannelTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(ChannelTemplateWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_template
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ChannelTemplate record);
}