package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.ChannelInfo;
import com.work.shop.bean.ChannelInfoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ChannelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ChannelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ChannelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int insert(ChannelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ChannelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ChannelInfo> selectByExample(ChannelInfoExample example);
    
    @ReadOnly
    List<ChannelInfo> findByChanneltype(Map map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @ReadOnly
    ChannelInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ChannelInfo record, @Param("example") ChannelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ChannelInfo record, @Param("example") ChannelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ChannelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ChannelInfo record);
    
    @Writer
    int updateByPrimaryKeys(Map map);
    
    
    
    
}