package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.ChannelApiInfo;
import com.work.shop.bean.ChannelApiInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelApiInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_info
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ChannelApiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_info
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ChannelApiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_info
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_info
     *
     * @mbggenerated
     */
    @Writer
    int insert(ChannelApiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_info
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ChannelApiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_info
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ChannelApiInfo> selectByExample(ChannelApiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_info
     *
     * @mbggenerated
     */
    ChannelApiInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ChannelApiInfo record, @Param("example") ChannelApiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ChannelApiInfo record, @Param("example") ChannelApiInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ChannelApiInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ChannelApiInfo record);
}