package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.ChannelApiName;
import com.work.shop.bean.ChannelApiNameExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelApiNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_name
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ChannelApiNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_name
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ChannelApiNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_name
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_name
     *
     * @mbggenerated
     */
    @Writer
    int insert(ChannelApiName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_name
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ChannelApiName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_name
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ChannelApiName> selectByExample(ChannelApiNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_name
     *
     * @mbggenerated
     */
    ChannelApiName selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_name
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ChannelApiName record, @Param("example") ChannelApiNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_name
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ChannelApiName record, @Param("example") ChannelApiNameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_name
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ChannelApiName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_api_name
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ChannelApiName record);
}