package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.ChannelVdepotInventory;
import com.work.shop.bean.ChannelVdepotInventoryExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelVdepotInventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ChannelVdepotInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ChannelVdepotInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    @Writer
    int insert(ChannelVdepotInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ChannelVdepotInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ChannelVdepotInventory> selectByExample(ChannelVdepotInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    ChannelVdepotInventory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ChannelVdepotInventory record, @Param("example") ChannelVdepotInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ChannelVdepotInventory record, @Param("example") ChannelVdepotInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ChannelVdepotInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_vdepot_inventory
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ChannelVdepotInventory record);
}