package com.work.shop.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.ChannelGoodsTicket;
import com.work.shop.bean.ChannelGoodsTicketExample;
import com.work.shop.vo.ChannelGoodsInfoVo;
import com.work.shop.vo.ChannelGoodsTicketVo;

public interface ChannelGoodsTicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_ticket
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ChannelGoodsTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_ticket
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ChannelGoodsTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_ticket
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_ticket
     *
     * @mbggenerated
     */
    @Writer
    int insert(ChannelGoodsTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_ticket
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ChannelGoodsTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_ticket
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ChannelGoodsTicketVo> selectByExample(ChannelGoodsTicketExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_ticket
     *
     * @mbggenerated
     */
    @Writer
    ChannelGoodsTicket selectByPrimaryKey(Integer id);
    
    @ReadOnly
    ChannelGoodsTicketVo selectVoByPrimaryKey(Integer id);
    
    @ReadOnly
    ChannelGoodsTicket selectByTicketCode(String ticketCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_ticket
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ChannelGoodsTicket record, @Param("example") ChannelGoodsTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_ticket
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ChannelGoodsTicket record, @Param("example") ChannelGoodsTicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_ticket
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ChannelGoodsTicket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_goods_ticket
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ChannelGoodsTicket record);
    
    @ReadOnly
    List<ChannelGoodsInfoVo> selectGoodsInfoByExample(ChannelGoodsTicketExample record);

    @ReadOnly
    int countGoodsInfoByExample(ChannelGoodsTicketExample record);

    @ReadOnly
    ChannelGoodsInfoVo selectGoodsInfoByPrimaryKey(Integer id);
    
    @ReadOnly
    int selectGoodsInfoCount(Map<String,Object> params);
    
    @ReadOnly
    List<ChannelGoodsInfoVo> selectGoodsInfo(Map<String,Object> params);
}