package com.work.shop.dao;

import java.util.List;
import java.util.Map;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.bean.ChannelGoodsVo;
import com.work.shop.bean.SystemRegion;
import com.work.shop.bean.SystemRegionArea;
import com.work.shop.vo.ChannelTemplateContentVo;

public interface GoodsPropertyMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    
    @ReadOnly
    List<ChannelGoodsVo> selectChannelGoods(Map<String, Object> map);
    
    @ReadOnly
    List<ChannelTemplateContentVo> selectModuleContent(Map<String, Object> map);
    
    @ReadOnly
    List<SystemRegionArea> selectSystemRegionArea(Map<String, Object> map);
    
    @ReadOnly
    List<SystemRegionArea> selectSystemRegionAreaLike(Map<String, Object> map);
    
    @ReadOnly
    List<SystemRegionArea> selectSystemRegion(Map<String, Object> map);
    
    @ReadOnly
    List<SystemRegionArea> selectSystemRegionLike(Map<String, Object> map);
   
    @ReadOnly
    List<SystemRegion> selectAllSystemRegion();
    
    @ReadOnly
    List<SystemRegionArea> selectNewSystemRegionAreaLike(Map<String, Object> map);
	
}