package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.GroupGoods;
import com.work.shop.bean.GroupGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(GroupGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(GroupGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_goods
     *
     * @mbggenerated
     */
    @Writer
    int insert(GroupGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_goods
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(GroupGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    List<GroupGoods> selectByExample(GroupGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_goods
     *
     * @mbggenerated
     */
    GroupGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") GroupGoods record, @Param("example") GroupGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") GroupGoods record, @Param("example") GroupGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(GroupGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(GroupGoods record);
}