package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.InterfaceProperties;
import com.work.shop.bean.InterfacePropertiesExample;
import com.work.shop.vo.InterfacePropertiesVo;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface InterfacePropertiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_properties
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(InterfacePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_properties
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(InterfacePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_properties
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_properties
     *
     * @mbggenerated
     */
    @Writer
    int insert(InterfaceProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_properties
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(InterfaceProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_properties
     *
     * @mbggenerated
     */
    @Writer
    List<InterfaceProperties> selectByExample(InterfacePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_properties
     *
     * @mbggenerated
     */
    InterfaceProperties selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_properties
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") InterfaceProperties record, @Param("example") InterfacePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_properties
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") InterfaceProperties record, @Param("example") InterfacePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_properties
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(InterfaceProperties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interface_properties
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(InterfaceProperties record);
    

    int  deleteByPrimaryKeys(Map record);
    
    /**
     * 查询密钥信息包括（店铺名称，渠道名称）
     ***/
    List<InterfacePropertiesVo> selectByVoExample(InterfacePropertiesExample example);
    
    /**
     * 查询密钥信息的数量包括（店铺名称，渠道名称）
     ***/
    int countByVoExample(InterfacePropertiesExample example);
    
}