package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.LuckyBagGoods;
import com.work.shop.bean.LuckyBagGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LuckyBagGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(LuckyBagGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(LuckyBagGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods
     *
     * @mbggenerated
     */
    @Writer
    int insert(LuckyBagGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(LuckyBagGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    List<LuckyBagGoods> selectByExample(LuckyBagGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods
     *
     * @mbggenerated
     */
    LuckyBagGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") LuckyBagGoods record, @Param("example") LuckyBagGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") LuckyBagGoods record, @Param("example") LuckyBagGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(LuckyBagGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(LuckyBagGoods record);
}