package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.LuckyBagSubset;
import com.work.shop.bean.LuckyBagSubsetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LuckyBagSubsetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_subset
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(LuckyBagSubsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_subset
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(LuckyBagSubsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_subset
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_subset
     *
     * @mbggenerated
     */
    @Writer
    int insert(LuckyBagSubset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_subset
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(LuckyBagSubset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_subset
     *
     * @mbggenerated
     */
    @ReadOnly
    List<LuckyBagSubset> selectByExample(LuckyBagSubsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_subset
     *
     * @mbggenerated
     */
    LuckyBagSubset selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_subset
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") LuckyBagSubset record, @Param("example") LuckyBagSubsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_subset
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") LuckyBagSubset record, @Param("example") LuckyBagSubsetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_subset
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(LuckyBagSubset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_subset
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(LuckyBagSubset record);
}