package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.LuckyBagGoodsRelation;
import com.work.shop.bean.LuckyBagGoodsRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LuckyBagGoodsRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods_relation
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(LuckyBagGoodsRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods_relation
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(LuckyBagGoodsRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods_relation
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods_relation
     *
     * @mbggenerated
     */
    @Writer
    int insert(LuckyBagGoodsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods_relation
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(LuckyBagGoodsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods_relation
     *
     * @mbggenerated
     */
    @ReadOnly
    List<LuckyBagGoodsRelation> selectByExample(LuckyBagGoodsRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods_relation
     *
     * @mbggenerated
     */
    LuckyBagGoodsRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods_relation
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") LuckyBagGoodsRelation record, @Param("example") LuckyBagGoodsRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods_relation
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") LuckyBagGoodsRelation record, @Param("example") LuckyBagGoodsRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods_relation
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(LuckyBagGoodsRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lucky_bag_goods_relation
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(LuckyBagGoodsRelation record);
}