package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.OmsChannelInfo;
import com.work.shop.bean.OmsChannelInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OmsChannelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(OmsChannelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(OmsChannelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer channelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int insert(OmsChannelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(OmsChannelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @ReadOnly
    List<OmsChannelInfo> selectByExample(OmsChannelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    OmsChannelInfo selectByPrimaryKey(Integer channelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") OmsChannelInfo record, @Param("example") OmsChannelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") OmsChannelInfo record, @Param("example") OmsChannelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(OmsChannelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(OmsChannelInfo record);
}