package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.ProductLibBrand;
import com.work.shop.bean.ProductLibBrandExample;
import com.work.shop.bean.ProductLibBrandWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductLibBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ProductLibBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ProductLibBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(String brandCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int insert(ProductLibBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ProductLibBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ProductLibBrandWithBLOBs> selectByExampleWithBLOBs(ProductLibBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ProductLibBrand> selectByExample(ProductLibBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    ProductLibBrandWithBLOBs selectByPrimaryKey(String brandCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ProductLibBrandWithBLOBs record, @Param("example") ProductLibBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") ProductLibBrandWithBLOBs record, @Param("example") ProductLibBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ProductLibBrand record, @Param("example") ProductLibBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ProductLibBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(ProductLibBrandWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_lib_brand
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ProductLibBrand record);
}