package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.ProductAttrValues;
import com.work.shop.bean.ProductAttrValuesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductAttrValuesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ProductAttrValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ProductAttrValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int insert(ProductAttrValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ProductAttrValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ProductAttrValues> selectByExample(ProductAttrValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    ProductAttrValues selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ProductAttrValues record, @Param("example") ProductAttrValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ProductAttrValues record, @Param("example") ProductAttrValuesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ProductAttrValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attr_values
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ProductAttrValues record);
}