package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.PromotionsLog;
import com.work.shop.bean.PromotionsLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromotionsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_log
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(PromotionsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_log
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(PromotionsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_log
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_log
     *
     * @mbggenerated
     */
    @Writer
    int insert(PromotionsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_log
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(PromotionsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_log
     *
     * @mbggenerated
     */
    @ReadOnly
    List<PromotionsLog> selectByExampleWithBLOBs(PromotionsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_log
     *
     * @mbggenerated
     */
    @ReadOnly
    List<PromotionsLog> selectByExample(PromotionsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_log
     *
     * @mbggenerated
     */
    PromotionsLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") PromotionsLog record, @Param("example") PromotionsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleWithBLOBs(@Param("record") PromotionsLog record, @Param("example") PromotionsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") PromotionsLog record, @Param("example") PromotionsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(PromotionsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeyWithBLOBs(PromotionsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_log
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(PromotionsLog record);
}