package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.PromotionsLimitMoney;
import com.work.shop.bean.PromotionsLimitMoneyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromotionsLimitMoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(PromotionsLimitMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(PromotionsLimitMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money
     *
     * @mbggenerated
     */
    @Writer
    int insert(PromotionsLimitMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(PromotionsLimitMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money
     *
     * @mbggenerated
     */
    @ReadOnly
    List<PromotionsLimitMoney> selectByExample(PromotionsLimitMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money
     *
     * @mbggenerated
     */
    PromotionsLimitMoney selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") PromotionsLimitMoney record, @Param("example") PromotionsLimitMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") PromotionsLimitMoney record, @Param("example") PromotionsLimitMoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(PromotionsLimitMoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(PromotionsLimitMoney record);
}