package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.PromotionsLimitSn;
import com.work.shop.bean.PromotionsLimitSnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromotionsLimitSnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_sn
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(PromotionsLimitSnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_sn
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(PromotionsLimitSnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_sn
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_sn
     *
     * @mbggenerated
     */
    @Writer
    int insert(PromotionsLimitSn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_sn
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(PromotionsLimitSn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_sn
     *
     * @mbggenerated
     */
    @ReadOnly
    List<PromotionsLimitSn> selectByExample(PromotionsLimitSnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_sn
     *
     * @mbggenerated
     */
    PromotionsLimitSn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_sn
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") PromotionsLimitSn record, @Param("example") PromotionsLimitSnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_sn
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") PromotionsLimitSn record, @Param("example") PromotionsLimitSnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_sn
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(PromotionsLimitSn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_sn
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(PromotionsLimitSn record);
}