package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.PromotionsLimitMoneyGoods;
import com.work.shop.bean.PromotionsLimitMoneyGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromotionsLimitMoneyGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(PromotionsLimitMoneyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(PromotionsLimitMoneyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money_goods
     *
     * @mbggenerated
     */
    @Writer
    int insert(PromotionsLimitMoneyGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money_goods
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(PromotionsLimitMoneyGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    List<PromotionsLimitMoneyGoods> selectByExample(PromotionsLimitMoneyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") PromotionsLimitMoneyGoods record, @Param("example") PromotionsLimitMoneyGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_limit_money_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") PromotionsLimitMoneyGoods record, @Param("example") PromotionsLimitMoneyGoodsExample example);
}