package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.PromotionsListGoods;
import com.work.shop.bean.PromotionsListGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromotionsListGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(PromotionsListGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(PromotionsListGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int insert(PromotionsListGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(PromotionsListGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    List<PromotionsListGoods> selectByExample(PromotionsListGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    PromotionsListGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") PromotionsListGoods record, @Param("example") PromotionsListGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") PromotionsListGoods record, @Param("example") PromotionsListGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(PromotionsListGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(PromotionsListGoods record);
}