package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.PromotionsLimitGoods;
import com.work.shop.bean.PromotionsLimitGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromotionsLimitGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(PromotionsLimitGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(PromotionsLimitGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int insert(PromotionsLimitGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(PromotionsLimitGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @ReadOnly
    List<PromotionsLimitGoods> selectByExample(PromotionsLimitGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    PromotionsLimitGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") PromotionsLimitGoods record, @Param("example") PromotionsLimitGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") PromotionsLimitGoods record, @Param("example") PromotionsLimitGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(PromotionsLimitGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_list_goods
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(PromotionsLimitGoods record);
}