package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.PromotionsInfo;
import com.work.shop.bean.PromotionsInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PromotionsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_info
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(PromotionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_info
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(PromotionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_info
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_info
     *
     * @mbggenerated
     */
    @Writer
    int insert(PromotionsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_info
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(PromotionsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_info
     *
     * @mbggenerated
     */
    @ReadOnly
    List<PromotionsInfo> selectByExample(PromotionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_info
     *
     * @mbggenerated
     */
    PromotionsInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") PromotionsInfo record, @Param("example") PromotionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") PromotionsInfo record, @Param("example") PromotionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(PromotionsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotions_info
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(PromotionsInfo record);
}