package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.ScChannelSku;
import com.work.shop.bean.ScChannelSkuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScChannelSkuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_channel_sku
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(ScChannelSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_channel_sku
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(ScChannelSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_channel_sku
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_channel_sku
     *
     * @mbggenerated
     */
    @Writer
    int insert(ScChannelSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_channel_sku
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(ScChannelSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_channel_sku
     *
     * @mbggenerated
     */
    @ReadOnly
    List<ScChannelSku> selectByExample(ScChannelSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_channel_sku
     *
     * @mbggenerated
     */
    ScChannelSku selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_channel_sku
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") ScChannelSku record, @Param("example") ScChannelSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_channel_sku
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") ScChannelSku record, @Param("example") ScChannelSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_channel_sku
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(ScChannelSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sc_channel_sku
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(ScChannelSku record);
}