package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.SystemRegion;
import com.work.shop.bean.SystemRegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(SystemRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(SystemRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Short regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    @Writer
    int insert(SystemRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(SystemRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    @ReadOnly
    List<SystemRegion> selectByExample(SystemRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    SystemRegion selectByPrimaryKey(Short regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") SystemRegion record, @Param("example") SystemRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") SystemRegion record, @Param("example") SystemRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(SystemRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(SystemRegion record);
}