package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.SystemRegionMatch;
import com.work.shop.bean.SystemRegionMatchExample;
import java.util.List;
//import org.apache.ibatis.annotations.Param;

public interface SystemRegionMatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(SystemRegionMatchExample example);

    /**//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     *//*
    @Writer
    int deleteByExample(SystemRegionMatchExample example);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     *//*
    @Writer
    int deleteByPrimaryKey(Short regionId);*/

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
   /* @Writer
    int insert(SystemRegionMatch record);*/

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(SystemRegionMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    @ReadOnly
    List<SystemRegionMatch> selectByExample(SystemRegionMatchExample example);

    /* *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    SystemRegionMatch selectByPrimaryKey(Integer regionId);
    
    SystemRegionMatch selectMatchByPrimaryKey(Integer regionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     *//*
    @Writer
    int updateByExampleSelective(@Param("record") SystemRegionMatch record, @Param("example") SystemRegionMatchExample example);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     *//*
    @Writer
    int updateByExample(@Param("record") SystemRegionMatch record, @Param("example") SystemRegionMatchExample example);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(SystemRegionMatch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_region
     *
     * @mbggenerated
     */
//    @Writer
//    int updateByPrimaryKey(SystemRegionMatch record);
}