package com.work.shop.dao;

import com.work.shop.invocation.ReadOnly;
import com.work.shop.invocation.Writer;
import com.work.shop.bean.TaoBaoO2OShop;
import com.work.shop.bean.TaoBaoO2OShopExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaoBaoO2OShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_o2o_shop
     *
     * @mbggenerated
     */
    @ReadOnly
    int countByExample(TaoBaoO2OShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_o2o_shop
     *
     * @mbggenerated
     */
    @Writer
    int deleteByExample(TaoBaoO2OShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_o2o_shop
     *
     * @mbggenerated
     */
    @Writer
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_o2o_shop
     *
     * @mbggenerated
     */
    @Writer
    int insert(TaoBaoO2OShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_o2o_shop
     *
     * @mbggenerated
     */
    @Writer
    int insertSelective(TaoBaoO2OShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_o2o_shop
     *
     * @mbggenerated
     */
    @ReadOnly
    List<TaoBaoO2OShop> selectByExample(TaoBaoO2OShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_o2o_shop
     *
     * @mbggenerated
     */
    TaoBaoO2OShop selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_o2o_shop
     *
     * @mbggenerated
     */
    @Writer
    int updateByExampleSelective(@Param("record") TaoBaoO2OShop record, @Param("example") TaoBaoO2OShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_o2o_shop
     *
     * @mbggenerated
     */
    @Writer
    int updateByExample(@Param("record") TaoBaoO2OShop record, @Param("example") TaoBaoO2OShopExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_o2o_shop
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKeySelective(TaoBaoO2OShop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table taobao_o2o_shop
     *
     * @mbggenerated
     */
    @Writer
    int updateByPrimaryKey(TaoBaoO2OShop record);
}